(self.AMP=self.AMP||[]).push({n:"amp-mustache",v:"1522422854768",f:(function(AMP){function ia(b,a){function c(){}c.prototype=a.prototype;b.prototype=new c;b.prototype.constructor=b;for(var e in a)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(a,e);d&&Object.defineProperty(b,e,d)}else b[e]=a[e]}function v(b,a){a=void 0===a?"":a;try{return decodeURIComponent(b)}catch(c){return a}};var ja=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function ka(b){var a=Object.create(null);if(!b)return a;for(var c;c=ja.exec(b);){var e=v(c[1],c[1]),d=c[2]?v(c[2],c[2]):"";a[e]=d}return a};self.log=self.log||{user:null,dev:null,userForEmbed:null};var H=self.log;function J(){if(!H.user)throw Error("failed to call initLogConstructor");return H.user};function M(b){return b||{}};function la(b){this.J=b;this.B=Object.create(null)}la.prototype.get=function(b){if(this.B[b])return this.B[b].access=Date.now(),this.B[b].payload};la.prototype.put=function(b,a){var c=this;this.B[b]={payload:a,access:Date.now()};var e=Object.keys(this.B);if(e.length>this.J){if(H.dev)b=H.dev;else throw Error("failed to call initLogConstructor");b.warn("lru-cache","Trimming template cache");e.sort(function(b,a){return c.B[a].access-c.B[b].access});delete this.B[e[e.length-1]]}};function N(b,a){return a.length>b.length?!1:0==b.lastIndexOf(a,0)};var W=self.AMP_CONFIG||{},ma=W.cdnUrl||"https://cdn.ampproject.org",na=("string"==typeof W.cdnProxyRegex?new RegExp(W.cdnProxyRegex):W.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;var oa=M({c:!0,v:!0,a:!0,ad:!0}),pa,ta,ua=/[?&]amp_js[^&]*/,Aa=/[?&]usqp[^&]*/;
function X(b){var a;pa||(pa=self.document.createElement("a"),ta=self.UrlCache||(self.UrlCache=new la(100)));var c=ta.get(b);if(c)return c;var e=pa;e.href=b;e.protocol||(e.href=e.href);var d={href:e.href,protocol:e.protocol,host:e.host,hostname:e.hostname,port:"0"==e.port?"":e.port,pathname:e.pathname,search:e.search,hash:e.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=e.origin&&
"null"!=e.origin?e.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;var f=d,h=f;if(a)return h;ta.put(b,h);return h}function Ba(b){"string"==typeof b&&(b=X(b));return na.test(b.origin)}
function Ca(b){"string"==typeof b&&(b=X(b));if(!Ba(b))return b.href;var a=b.pathname.split("/"),c=a[1];J().assert(oa[c],"Unknown path prefix in url %s",b.href);var e=a[2],d="s"==e?"https://"+decodeURIComponent(a[3]):"http://"+decodeURIComponent(e);J().assert(0<d.indexOf("."),"Expected a . in origin %s",d);a.splice(1,"s"==e?3:2);a=d+a.join("/");c=(c=b.search)&&"?"!=c?(c=c.replace(ua,"").replace(Aa,"").replace(/^[?&]/,""))?"?"+c:"":"";return a+c+(b.hash||"")}
function Da(b,a){"string"==typeof a&&(a=X(a));var c;if("function"==typeof URL)c=(new URL(b,a.href)).toString();else{c=b;var e=a;"string"==typeof e&&(e=X(e));c=c.replace(/\\/g,"/");var d=X(c);c=N(c.toLowerCase(),d.protocol)?d.href:N(c,"//")?e.protocol+c:N(c,"/")?e.origin+c:e.origin+e.pathname.replace(/\/[^/]*$/,"/")+c}return c}function Ea(b){var a=X(b),c=ka(a.search);J().assert(!("__amp_source_origin"in c),"Source origin is not allowed in %s",b)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function Fa(b){if("content"in b)return b.content.cloneNode(!0);var a=b.ownerDocument.createDocumentFragment(),c=a,e=c.ownerDocument.createDocumentFragment();for(b=b.firstChild;b;b=b.nextSibling)e.appendChild(b.cloneNode(!0));c.appendChild(e);return a}function Ga(b,a){for(var c=0,e;void 0!==(e=b[c]);c++)a(e,c)};function Ha(b){a:{var a;try{a=b.document.cookie}catch(p){a=""}if(b=a)for(b=b.split(";"),a=0;a<b.length;a++){var c=b[a].trim(),e=c.indexOf("="),d;if(d=-1!=e)d=c.substring(0,e).trim(),d="AMP_EXP"==v(d,void 0);if(d){b=c.substring(e+1).trim();b=v(b,b);break a}}b=null}var f=b,h=f?f.split(/\s*,\s*/g):[];b=Object.create(null);for(a=0;a<h.length;a++)0!=h[a].length&&("-"==h[a][0]?b[h[a].substr(1)]=!1:b[h[a]]=!0);return b};var Ia=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function Ja(b){for(var a=[],c;c=Ia.exec(b);){var e=c[1],d=void 0,f;if(c[2]){var h=c[3].toLowerCase();if("w"==h)d=parseInt(c[2],10);else if("x"==h)f=parseFloat(c[2]);else continue}else f=1;a.push({url:e,width:d,dpr:f})}return new Y(a)}
function Y(b){J().assert(0<b.length,"Srcset must have at least one source");this.F=b;for(var a=!1,c=!1,e=0;e<b.length;e++)var d=b[e],a=a||!!d.width,c=c||!!d.dpr;J().assert(!!(a^c),"Srcset must have width or dpr sources, but not both");b.sort(a?Ka:La);this.I=a;this.K=c}
Y.prototype.select=function(b,a){if(this.I){a*=b;b=this.F;for(var c=0,e=Infinity,d=Infinity,f=0;f<b.length;f++){var h=b[f].width,p=Math.abs(h-a);if(p<=1.1*e||1.2<a/d)c=f,e=p,d=h;else break}}else for(b=this.F,c=0,e=Infinity,d=0;d<b.length;d++)if(f=Math.abs(b[d].dpr-a),f<=e)c=d,e=f;else break;a=c;return this.F[a].url};Y.prototype.getUrls=function(){return this.F.map(function(b){return b.url})};
Y.prototype.stringify=function(b){for(var a=[],c=this.F,e=0;e<c.length;e++){var d=c[e],f=d.url;b&&(f=b(f));f=this.I?f+(" "+d.width+"w"):f+(" "+d.dpr+"x");a.push(f)}return a.join(", ")};function Ka(b,a){J().assert(b.width!=a.width,"Duplicate width: %s",b.width);return b.width-a.width}function La(b,a){J().assert(b.dpr!=a.dpr,"Duplicate dpr: %s",b.dpr);return b.dpr-a.dpr};var Ma=function(){function b(b){var a=(""+b).match(w);return a?new g(k(a[1]),k(a[2]),k(a[3]),k(a[4]),k(a[5]),k(a[6]),k(a[7])):null}function a(b,a,z,h,f,k,p){b=new g(e(b,u),e(a,u),c(z),0<h?h.toString():null,e(f,C),null,c(p));k&&("string"===typeof k?b.setRawQuery(k.replace(/[^?&=0-9A-Za-z_\-~.%]/g,d)):b.setAllParameters(k));return b}function c(b){return"string"==typeof b?encodeURIComponent(b):null}function e(b,a){return"string"==typeof b?encodeURI(b).replace(a,d):null}function d(b){var a=b.charCodeAt(0);
return"%"+"0123456789ABCDEF".charAt(a>>4&15)+"0123456789ABCDEF".charAt(a&15)}function f(b){return b.replace(/(^|\/)\.(?:\/|$)/g,"$1").replace(/\/{2,}/g,"/")}function h(b){if(null===b)return null;b=f(b);for(var a=S,r;(r=b.replace(a,"$1"))!=b;b=r);return b}function p(b,a){var r=b.clone(),c=a.hasScheme();c?r.setRawScheme(a.getRawScheme()):c=a.hasCredentials();c?r.setRawCredentials(a.getRawCredentials()):c=a.hasDomain();c?r.setRawDomain(a.getRawDomain()):c=a.hasPort();var e=a.getRawPath(),d=h(e);if(c)r.setPort(a.getPort()),
d=d&&d.replace(A,"");else if(c=!!e){if(47!==d.charCodeAt(0))var g=h(r.getRawPath()||"").replace(A,""),f=g.lastIndexOf("/")+1,d=h((f?g.substring(0,f):"")+h(e)).replace(A,"")}else d=d&&d.replace(A,""),d!==e&&r.setRawPath(d);c?r.setRawPath(d):c=a.hasQuery();c?r.setRawQuery(a.getRawQuery()):c=a.hasFragment();c&&r.setRawFragment(a.getRawFragment());return r}function g(b,a,c,e,d,g,f){this.A=b;this.m=a;this.o=c;this.C=e;this.l=d;this.j=g;this.w=f;this.h=null}function k(b){return"string"==typeof b&&0<b.length?
b:null}var T=/(\/|^)(?:[^./][^/]*|\.{2,}(?:[^./][^/]*)|\.{3,}[^/]*)\/\.\.(?:\/|$)/,S=new RegExp(T),A=/^(?:\.\.\/)*(?:\.\.$)?/;g.prototype.toString=function(){var b=[];null!==this.A&&b.push(this.A,":");null!==this.o&&(b.push("//"),null!==this.m&&b.push(this.m,"@"),b.push(this.o),null!==this.C&&b.push(":",this.C.toString()));null!==this.l&&b.push(this.l);null!==this.j&&b.push("?",this.j);null!==this.w&&b.push("#",this.w);return b.join("")};g.prototype.clone=function(){return new g(this.A,this.m,this.o,
this.C,this.l,this.j,this.w)};g.prototype.getScheme=function(){return this.A&&decodeURIComponent(this.A).toLowerCase()};g.prototype.getRawScheme=function(){return this.A};g.prototype.setScheme=function(b){this.A=e(b,u);return this};g.prototype.setRawScheme=function(b){this.A=b?b:null;return this};g.prototype.hasScheme=function(){return null!==this.A};g.prototype.getCredentials=function(){return this.m&&decodeURIComponent(this.m)};g.prototype.getRawCredentials=function(){return this.m};g.prototype.setCredentials=
function(b){this.m=e(b,u);return this};g.prototype.setRawCredentials=function(b){this.m=b?b:null;return this};g.prototype.hasCredentials=function(){return null!==this.m};g.prototype.getDomain=function(){return this.o&&decodeURIComponent(this.o)};g.prototype.getRawDomain=function(){return this.o};g.prototype.setDomain=function(b){return this.setRawDomain(b&&encodeURIComponent(b))};g.prototype.setRawDomain=function(b){this.o=b?b:null;return this.setRawPath(this.l)};g.prototype.hasDomain=function(){return null!==
this.o};g.prototype.getPort=function(){return this.C&&decodeURIComponent(this.C)};g.prototype.setPort=function(b){if(b){b=Number(b);if(b!==(b&65535))throw Error("Bad port number "+b);this.C=""+b}else this.C=null;return this};g.prototype.hasPort=function(){return null!==this.C};g.prototype.getPath=function(){return this.l&&decodeURIComponent(this.l)};g.prototype.getRawPath=function(){return this.l};g.prototype.setPath=function(b){return this.setRawPath(e(b,C))};g.prototype.setRawPath=function(b){b?
(b=String(b),this.l=!this.o||/^\//.test(b)?b:"/"+b):this.l=null;return this};g.prototype.hasPath=function(){return null!==this.l};g.prototype.getQuery=function(){return this.j&&decodeURIComponent(this.j).replace(/\+/g," ")};g.prototype.getRawQuery=function(){return this.j};g.prototype.setQuery=function(b){this.h=null;this.j=c(b);return this};g.prototype.setRawQuery=function(b){this.h=null;this.j=b?b:null;return this};g.prototype.hasQuery=function(){return null!==this.j};g.prototype.setAllParameters=
function(b){if("object"===typeof b&&!(b instanceof Array)&&(b instanceof Object||"[object Array]"!==Object.prototype.toString.call(b))){var a=[],c=-1,e;for(e in b){var d=b[e];"string"===typeof d&&(a[++c]=e,a[++c]=d)}b=a}this.h=null;for(var g=[],r="",f=0;f<b.length;)e=b[f++],d=b[f++],g.push(r,encodeURIComponent(e.toString())),r="&",d&&g.push("=",encodeURIComponent(d.toString()));this.j=g.join("");return this};g.prototype.D=function(){if(!this.h){var b=this.j;if(b){for(var a=b.split(/[&\?]/),b=[],c=
-1,e=0;e<a.length;++e){var d=a[e].match(/^([^=]*)(?:=(.*))?$/);b[++c]=decodeURIComponent(d[1]).replace(/\+/g," ");b[++c]=decodeURIComponent(d[2]||"").replace(/\+/g," ")}this.h=b}else this.h=[]}};g.prototype.setParameterValues=function(b,a){"string"===typeof a&&(a=[a]);this.D();for(var c=0,e=this.h,d=[],g=0;g<e.length;g+=2)b===e[g]?c<a.length&&d.push(b,a[c++]):d.push(e[g],e[g+1]);for(;c<a.length;)d.push(b,a[c++]);this.setAllParameters(d);return this};g.prototype.removeParameter=function(b){return this.setParameterValues(b,
[])};g.prototype.getAllParameters=function(){this.D();return this.h.slice(0,this.h.length)};g.prototype.getParameterValues=function(b){this.D();for(var a=[],c=0;c<this.h.length;c+=2)b===this.h[c]&&a.push(this.h[c+1]);return a};g.prototype.getParameterMap=function(){this.D();for(var b={},a=0;a<this.h.length;a+=2){var c=this.h[a++],e=this.h[a++];c in b?b[c].push(e):b[c]=[e]}return b};g.prototype.getParameterValue=function(b){this.D();for(var a=0;a<this.h.length;a+=2)if(b===this.h[a])return this.h[a+
1];return null};g.prototype.getFragment=function(){return this.w&&decodeURIComponent(this.w)};g.prototype.getRawFragment=function(){return this.w};g.prototype.setFragment=function(b){this.w=b?encodeURIComponent(b):null;return this};g.prototype.setRawFragment=function(b){this.w=b?b:null;return this};g.prototype.hasFragment=function(){return null!==this.w};var w=/^(?:([^:/?#]+):)?(?:\/\/(?:([^/?#]*)@)?([^/?#:@]*)(?::([0-9]+))?)?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,u=/[#\/\?@]/g,C=/[\#\?]/g;g.parse=b;
g.create=a;g.resolve=p;g.collapse_dots=h;g.utils={mimeTypeOf:function(a){var c=b(a);return/\.html$/.test(c.getPath())?"text/html":"application/javascript"},resolve:function(a,c){return a?p(b(a),b(c)).toString():""+c}};return g}(),Z={atype:{NONE:0,URI:1,URI_FRAGMENT:11,SCRIPT:2,STYLE:3,HTML:12,ID:4,IDREF:5,IDREFS:6,GLOBAL_NAME:7,LOCAL_NAME:8,CLASSES:9,FRAME_TARGET:10,MEDIA_QUERY:13}};Z.atype=Z.atype;
Z.ATTRIBS={"*::class":9,"*::dir":0,"*::draggable":0,"*::hidden":0,"*::id":4,"*::inert":0,"*::itemprop":0,"*::itemref":6,"*::itemscope":0,"*::lang":0,"*::onblur":2,"*::onchange":2,"*::onclick":2,"*::ondblclick":2,"*::onerror":2,"*::onfocus":2,"*::onkeydown":2,"*::onkeypress":2,"*::onkeyup":2,"*::onload":2,"*::onmousedown":2,"*::onmousemove":2,"*::onmouseout":2,"*::onmouseover":2,"*::onmouseup":2,"*::onreset":2,"*::onscroll":2,"*::onselect":2,"*::onsubmit":2,"*::ontouchcancel":2,"*::ontouchend":2,"*::ontouchenter":2,
"*::ontouchleave":2,"*::ontouchmove":2,"*::ontouchstart":2,"*::onunload":2,"*::spellcheck":0,"*::style":3,"*::tabindex":0,"*::title":0,"*::translate":0,"a::accesskey":0,"a::coords":0,"a::href":1,"a::hreflang":0,"a::name":7,"a::onblur":2,"a::onfocus":2,"a::shape":0,"a::target":10,"a::type":0,"area::accesskey":0,"area::alt":0,"area::coords":0,"area::href":1,"area::nohref":0,"area::onblur":2,"area::onfocus":2,"area::shape":0,"area::target":10,"audio::controls":0,"audio::loop":0,"audio::mediagroup":5,
"audio::muted":0,"audio::preload":0,"audio::src":1,"bdo::dir":0,"blockquote::cite":1,"br::clear":0,"button::accesskey":0,"button::disabled":0,"button::name":8,"button::onblur":2,"button::onfocus":2,"button::type":0,"button::value":0,"canvas::height":0,"canvas::width":0,"caption::align":0,"col::align":0,"col::char":0,"col::charoff":0,"col::span":0,"col::valign":0,"col::width":0,"colgroup::align":0,"colgroup::char":0,"colgroup::charoff":0,"colgroup::span":0,"colgroup::valign":0,"colgroup::width":0,
"command::checked":0,"command::command":5,"command::disabled":0,"command::icon":1,"command::label":0,"command::radiogroup":0,"command::type":0,"data::value":0,"del::cite":1,"del::datetime":0,"details::open":0,"dir::compact":0,"div::align":0,"dl::compact":0,"fieldset::disabled":0,"font::color":0,"font::face":0,"font::size":0,"form::accept":0,"form::action":1,"form::autocomplete":0,"form::enctype":0,"form::method":0,"form::name":7,"form::novalidate":0,"form::onreset":2,"form::onsubmit":2,"form::target":10,
"h1::align":0,"h2::align":0,"h3::align":0,"h4::align":0,"h5::align":0,"h6::align":0,"hr::align":0,"hr::noshade":0,"hr::size":0,"hr::width":0,"iframe::align":0,"iframe::frameborder":0,"iframe::height":0,"iframe::marginheight":0,"iframe::marginwidth":0,"iframe::width":0,"img::align":0,"img::alt":0,"img::border":0,"img::height":0,"img::hspace":0,"img::ismap":0,"img::name":7,"img::src":1,"img::usemap":11,"img::vspace":0,"img::width":0,"input::accept":0,"input::accesskey":0,"input::align":0,"input::alt":0,
"input::autocomplete":0,"input::checked":0,"input::disabled":0,"input::inputmode":0,"input::ismap":0,"input::list":5,"input::max":0,"input::maxlength":0,"input::min":0,"input::multiple":0,"input::name":8,"input::onblur":2,"input::onchange":2,"input::onfocus":2,"input::onselect":2,"input::pattern":0,"input::placeholder":0,"input::readonly":0,"input::required":0,"input::size":0,"input::src":1,"input::step":0,"input::type":0,"input::usemap":11,"input::value":0,"ins::cite":1,"ins::datetime":0,"label::accesskey":0,
"label::for":5,"label::onblur":2,"label::onfocus":2,"legend::accesskey":0,"legend::align":0,"li::type":0,"li::value":0,"map::name":7,"menu::compact":0,"menu::label":0,"menu::type":0,"meter::high":0,"meter::low":0,"meter::max":0,"meter::min":0,"meter::optimum":0,"meter::value":0,"ol::compact":0,"ol::reversed":0,"ol::start":0,"ol::type":0,"optgroup::disabled":0,"optgroup::label":0,"option::disabled":0,"option::label":0,"option::selected":0,"option::value":0,"output::for":6,"output::name":8,"p::align":0,
"pre::width":0,"progress::max":0,"progress::min":0,"progress::value":0,"q::cite":1,"select::autocomplete":0,"select::disabled":0,"select::multiple":0,"select::name":8,"select::onblur":2,"select::onchange":2,"select::onfocus":2,"select::required":0,"select::size":0,"source::type":0,"table::align":0,"table::bgcolor":0,"table::border":0,"table::cellpadding":0,"table::cellspacing":0,"table::frame":0,"table::rules":0,"table::summary":0,"table::width":0,"tbody::align":0,"tbody::char":0,"tbody::charoff":0,
"tbody::valign":0,"td::abbr":0,"td::align":0,"td::axis":0,"td::bgcolor":0,"td::char":0,"td::charoff":0,"td::colspan":0,"td::headers":6,"td::height":0,"td::nowrap":0,"td::rowspan":0,"td::scope":0,"td::valign":0,"td::width":0,"template::type":0,"textarea::accesskey":0,"textarea::autocomplete":0,"textarea::cols":0,"textarea::disabled":0,"textarea::inputmode":0,"textarea::name":8,"textarea::onblur":2,"textarea::onchange":2,"textarea::onfocus":2,"textarea::onselect":2,"textarea::placeholder":0,"textarea::readonly":0,
"textarea::required":0,"textarea::rows":0,"textarea::wrap":0,"tfoot::align":0,"tfoot::char":0,"tfoot::charoff":0,"tfoot::valign":0,"th::abbr":0,"th::align":0,"th::axis":0,"th::bgcolor":0,"th::char":0,"th::charoff":0,"th::colspan":0,"th::headers":6,"th::height":0,"th::nowrap":0,"th::rowspan":0,"th::scope":0,"th::valign":0,"th::width":0,"thead::align":0,"thead::char":0,"thead::charoff":0,"thead::valign":0,"tr::align":0,"tr::bgcolor":0,"tr::char":0,"tr::charoff":0,"tr::valign":0,"track::default":0,"track::kind":0,
"track::label":0,"track::srclang":0,"ul::compact":0,"ul::type":0,"video::controls":0,"video::height":0,"video::loop":0,"video::mediagroup":5,"video::muted":0,"video::poster":1,"video::preload":0,"video::src":1,"video::width":0};Z.ATTRIBS=Z.ATTRIBS;Z.eflags={OPTIONAL_ENDTAG:1,EMPTY:2,CDATA:4,RCDATA:8,UNSAFE:16,FOLDABLE:32,SCRIPT:64,STYLE:128,VIRTUALIZED:256};Z.eflags=Z.eflags;
Z.ELEMENTS={a:0,abbr:0,acronym:0,address:0,applet:272,area:2,article:0,aside:0,audio:0,b:0,base:274,basefont:274,bdi:0,bdo:0,big:0,blockquote:0,body:305,br:2,button:0,canvas:0,caption:0,center:0,cite:0,code:0,col:2,colgroup:1,command:2,data:0,datalist:0,dd:1,del:0,details:0,dfn:0,dialog:272,dir:0,div:0,dl:0,dt:1,em:0,fieldset:0,figcaption:0,figure:0,font:0,footer:0,form:0,frame:274,frameset:272,h1:0,h2:0,h3:0,h4:0,h5:0,h6:0,head:305,header:0,hgroup:0,hr:2,html:305,i:0,iframe:4,img:2,input:2,ins:0,
isindex:274,kbd:0,keygen:274,label:0,legend:0,li:1,link:274,map:0,mark:0,menu:0,meta:274,meter:0,nav:0,nobr:0,noembed:276,noframes:276,noscript:276,object:272,ol:0,optgroup:0,option:1,output:0,p:1,param:274,pre:0,progress:0,q:0,s:0,samp:0,script:84,section:0,select:0,small:0,source:2,span:0,strike:0,strong:0,style:148,sub:0,summary:0,sup:0,table:0,tbody:1,td:1,template:4,textarea:8,tfoot:1,th:1,thead:1,time:0,title:280,tr:1,track:2,tt:0,u:0,ul:0,"var":0,video:0,wbr:2};Z.ELEMENTS=Z.ELEMENTS;
Z.ELEMENT_DOM_INTERFACES={a:"HTMLAnchorElement",abbr:"HTMLElement",acronym:"HTMLElement",address:"HTMLElement",applet:"HTMLAppletElement",area:"HTMLAreaElement",article:"HTMLElement",aside:"HTMLElement",audio:"HTMLAudioElement",b:"HTMLElement",base:"HTMLBaseElement",basefont:"HTMLBaseFontElement",bdi:"HTMLElement",bdo:"HTMLElement",big:"HTMLElement",blockquote:"HTMLQuoteElement",body:"HTMLBodyElement",br:"HTMLBRElement",button:"HTMLButtonElement",canvas:"HTMLCanvasElement",caption:"HTMLTableCaptionElement",
center:"HTMLElement",cite:"HTMLElement",code:"HTMLElement",col:"HTMLTableColElement",colgroup:"HTMLTableColElement",command:"HTMLCommandElement",data:"HTMLElement",datalist:"HTMLDataListElement",dd:"HTMLElement",del:"HTMLModElement",details:"HTMLDetailsElement",dfn:"HTMLElement",dialog:"HTMLDialogElement",dir:"HTMLDirectoryElement",div:"HTMLDivElement",dl:"HTMLDListElement",dt:"HTMLElement",em:"HTMLElement",fieldset:"HTMLFieldSetElement",figcaption:"HTMLElement",figure:"HTMLElement",font:"HTMLFontElement",
footer:"HTMLElement",form:"HTMLFormElement",frame:"HTMLFrameElement",frameset:"HTMLFrameSetElement",h1:"HTMLHeadingElement",h2:"HTMLHeadingElement",h3:"HTMLHeadingElement",h4:"HTMLHeadingElement",h5:"HTMLHeadingElement",h6:"HTMLHeadingElement",head:"HTMLHeadElement",header:"HTMLElement",hgroup:"HTMLElement",hr:"HTMLHRElement",html:"HTMLHtmlElement",i:"HTMLElement",iframe:"HTMLIFrameElement",img:"HTMLImageElement",input:"HTMLInputElement",ins:"HTMLModElement",isindex:"HTMLUnknownElement",kbd:"HTMLElement",
keygen:"HTMLKeygenElement",label:"HTMLLabelElement",legend:"HTMLLegendElement",li:"HTMLLIElement",link:"HTMLLinkElement",map:"HTMLMapElement",mark:"HTMLElement",menu:"HTMLMenuElement",meta:"HTMLMetaElement",meter:"HTMLMeterElement",nav:"HTMLElement",nobr:"HTMLElement",noembed:"HTMLElement",noframes:"HTMLElement",noscript:"HTMLElement",object:"HTMLObjectElement",ol:"HTMLOListElement",optgroup:"HTMLOptGroupElement",option:"HTMLOptionElement",output:"HTMLOutputElement",p:"HTMLParagraphElement",param:"HTMLParamElement",
pre:"HTMLPreElement",progress:"HTMLProgressElement",q:"HTMLQuoteElement",s:"HTMLElement",samp:"HTMLElement",script:"HTMLScriptElement",section:"HTMLElement",select:"HTMLSelectElement",small:"HTMLElement",source:"HTMLSourceElement",span:"HTMLSpanElement",strike:"HTMLElement",strong:"HTMLElement",style:"HTMLStyleElement",sub:"HTMLElement",summary:"HTMLElement",sup:"HTMLElement",table:"HTMLTableElement",tbody:"HTMLTableSectionElement",td:"HTMLTableDataCellElement",template:"HTMLTemplateElement",textarea:"HTMLTextAreaElement",
tfoot:"HTMLTableSectionElement",th:"HTMLTableHeaderCellElement",thead:"HTMLTableSectionElement",time:"HTMLTimeElement",title:"HTMLTitleElement",tr:"HTMLTableRowElement",track:"HTMLTrackElement",tt:"HTMLElement",u:"HTMLElement",ul:"HTMLUListElement","var":"HTMLElement",video:"HTMLVideoElement",wbr:"HTMLElement"};Z.ELEMENT_DOM_INTERFACES=Z.ELEMENT_DOM_INTERFACES;Z.ueffects={NOT_LOADED:0,SAME_DOCUMENT:1,NEW_DOCUMENT:2};Z.ueffects=Z.ueffects;
Z.URIEFFECTS={"a::href":2,"area::href":2,"audio::src":1,"blockquote::cite":0,"command::icon":1,"del::cite":0,"form::action":2,"img::src":1,"input::src":1,"ins::cite":0,"q::cite":0,"video::poster":1,"video::src":1};Z.URIEFFECTS=Z.URIEFFECTS;Z.ltypes={UNSANDBOXED:2,SANDBOXED:1,DATA:0};Z.ltypes=Z.ltypes;
Z.LOADERTYPES={"a::href":2,"area::href":2,"audio::src":2,"blockquote::cite":2,"command::icon":1,"del::cite":2,"form::action":2,"img::src":1,"input::src":1,"ins::cite":2,"q::cite":2,"video::poster":1,"video::src":2};Z.LOADERTYPES=Z.LOADERTYPES;
var Na=function(b){function a(b){if(da.hasOwnProperty(b))return da[b];var a=b.match(va);return a?String.fromCharCode(parseInt(a[1],10)):(a=b.match(wa))?String.fromCharCode(parseInt(a[1],16)):ea&&O.test(b)?(ea.innerHTML="&"+b+";",a=ea.textContent,da[b]=a):"&"+b+";"}function c(b,c){return a(c)}function e(b){return b.replace(P,"")}function d(b){return b.replace(K,c)}function f(b){return(""+b).replace(n,"&amp;").replace(B,"&lt;").replace(F,"&gt;").replace(Q,"&#34;")}function h(b){return b.replace(l,"&amp;$1").replace(B,
"&lt;").replace(F,"&gt;")}function p(b){var a={cdata:b.cdata||b.cdata,comment:b.comment||b.comment,endDoc:b.endDoc||b.endDoc,endTag:b.endTag||b.endTag,pcdata:b.pcdata||b.pcdata,rcdata:b.rcdata||b.rcdata,startDoc:b.startDoc||b.startDoc,startTag:b.startTag||b.startTag};return function(b,c){var e=a,d=T(b);k(e,d,0,{noMoreGT:!1,noMoreEndComments:!1},c)}}function g(b,a,c,e,d){return function(){k(b,a,c,e,d)}}function k(a,c,e,d,m){try{a.startDoc&&0==e&&a.startDoc(m);for(var t,q,L,f=e,G=c.length;f<G;){var h=
c[f++],k=c[f];switch(h){case "&":U.test(k)?(a.pcdata&&a.pcdata("&"+k,m,y,g(a,c,f,d,m)),f++):a.pcdata&&a.pcdata("&amp;",m,y,g(a,c,f,d,m));break;case "</":(t=/^([-\w:]+)[^\'\"]*/.exec(k))?t[0].length===k.length&&">"===c[f+1]?(f+=2,L=t[1].toLowerCase(),a.endTag&&a.endTag(L,m,y,g(a,c,f,d,m))):f=S(c,f,a,m,y,d):a.pcdata&&a.pcdata("&lt;/",m,y,g(a,c,f,d,m));break;case "<":if(t=/^([-\w:]+)\s*\/?/.exec(k))if(t[0].length===k.length&&">"===c[f+1]){f+=2;L=t[1].toLowerCase();a.startTag&&a.startTag(L,[],m,y,g(a,
c,f,d,m));var n=b.ELEMENTS[L];n&xa&&(f=w(c,{name:L,next:f,eflags:n},a,m,y,d))}else f=A(c,f,a,m,y,d);else a.pcdata&&a.pcdata("&lt;",m,y,g(a,c,f,d,m));break;case "\x3c!--":if(!d.noMoreEndComments){for(q=f+1;q<G&&(">"!==c[q]||!/--$/.test(c[q-1]));q++);if(q<G){if(a.comment){var l=c.slice(f,q).join("");a.comment(l.substr(0,l.length-2),m,y,g(a,c,q+1,d,m))}f=q+1}else d.noMoreEndComments=!0}d.noMoreEndComments&&a.pcdata&&a.pcdata("&lt;!--",m,y,g(a,c,f,d,m));break;case "<!":if(/^\w/.test(k)){if(!d.noMoreGT){for(q=
f+1;q<G&&">"!==c[q];q++);q<G?f=q+1:d.noMoreGT=!0}d.noMoreGT&&a.pcdata&&a.pcdata("&lt;!",m,y,g(a,c,f,d,m))}else a.pcdata&&a.pcdata("&lt;!",m,y,g(a,c,f,d,m));break;case "<?":if(!d.noMoreGT){for(q=f+1;q<G&&">"!==c[q];q++);q<G?f=q+1:d.noMoreGT=!0}d.noMoreGT&&a.pcdata&&a.pcdata("&lt;?",m,y,g(a,c,f,d,m));break;case ">":a.pcdata&&a.pcdata("&gt;",m,y,g(a,c,f,d,m));break;case "":break;default:a.pcdata&&a.pcdata(h,m,y,g(a,c,f,d,m))}}a.endDoc&&a.endDoc(m)}catch(ya){if(ya!==y)throw ya;}}function T(b){var a=/(<\/|<\!--|<[!?]|[&<>])/g;
b+="";if(ra)return b.split(a);for(var c=[],d=0,e;null!==(e=a.exec(b));)c.push(b.substring(d,e.index)),c.push(e[0]),d=e.index+e[0].length;c.push(b.substring(d));return c}function S(b,a,c,d,e,f){var m=u(b,a);if(!m)return b.length;c.endTag&&c.endTag(m.name,d,e,g(c,b,a,f,d));return m.next}function A(b,a,c,d,e,f){a=u(b,a);if(!a)return b.length;c.startTag&&c.startTag(a.name,a.attrs,d,e,g(c,b,a.next,f,d));return a.eflags&xa?w(b,a,c,d,e,f):a.next}function w(a,c,d,e,f,k){var m=a.length;sa.hasOwnProperty(c.name)||
(sa[c.name]=new RegExp("^"+c.name+"(?:[\\s\\/]|$)","i"));for(var q=sa[c.name],L=c.next,t=c.next+1;t<m&&("</"!==a[t-1]||!q.test(a[t]));t++);t<m&&--t;var G=a.slice(L,t).join("");if(c.eflags&b.eflags.CDATA)d.cdata&&d.cdata(G,e,f,g(d,a,t,k,e));else if(c.eflags&b.eflags.RCDATA)d.rcdata&&d.rcdata(h(G),e,f,g(d,a,t,k,e));else throw Error("bug");return t}function u(a,c){var d=/^([-\w:]+)/.exec(a[c]),e={};e.name=d[1].toLowerCase();e.eflags=b.ELEMENTS[e.name];var f=a[c].substr(d[0].length);c+=1;for(var g=a.length;c<
g&&">"!==a[c];c++)f+=a[c];if(!(g<=c)){for(var q=[];""!==f;)if(d=I.exec(f))if(d[4]&&!d[5]||d[6]&&!d[7]){for(var k=d[4]||d[6],h=!1,t=[f,a[c++]];c<g;c++){if(h){if(">"===a[c])break}else 0<=a[c].indexOf(k)&&(h=!0);t.push(a[c])}if(g<=c)break;f=t.join("")}else{var n=d[1].toLowerCase(),l=d[2]?C(d[3]):"";q.push(n,l);f=f.substr(d[0].length)}else f=f.replace(/^[\s\S][^a-z\s]*/,"");e.attrs=q;e.next=c+1;return e}}function C(b){var a=b.charCodeAt(0);if(34===a||39===a)b=b.substr(1,b.length-2);return d(e(b))}function r(a){function c(b,
a){e||a.push(b)}var d,e;return p({startDoc:function(){d=[];e=!1},startTag:function(c,g,k){if(!e&&b.ELEMENTS.hasOwnProperty(c)){var m=b.ELEMENTS[c];if(!(m&b.eflags.FOLDABLE)){var q=a(c,g);if(q){if("object"!==typeof q)throw Error("tagPolicy did not return object (old API?)");if("attribs"in q)g=q.attribs;else throw Error("tagPolicy gave no attribs");var h,t;"tagName"in q?(t=q.tagName,h=b.ELEMENTS[t]):(t=c,h=m);if(m&b.eflags.OPTIONAL_ENDTAG){var n=d[d.length-1];!n||n.orig!==c||n.rep===t&&c===t||k.push("</",
n.rep,">")}m&b.eflags.EMPTY||d.push({orig:c,rep:t});k.push("<",t);for(var l=0,p=g.length;l<p;l+=2){var F=g[l],V=g[l+1];null!==V&&void 0!==V&&k.push(" ",F,'="',f(V),'"')}k.push(">");m&b.eflags.EMPTY&&!(h&b.eflags.EMPTY)&&k.push("</",t,">")}else e=!(m&b.eflags.EMPTY)}}},endTag:function(a,c){if(e)e=!1;else if(b.ELEMENTS.hasOwnProperty(a)){var f=b.ELEMENTS[a];if(!(f&(b.eflags.EMPTY|b.eflags.FOLDABLE))){if(f&b.eflags.OPTIONAL_ENDTAG)for(f=d.length;0<=--f;){var g=d[f].orig;if(g===a)break;if(!(b.ELEMENTS[g]&
b.eflags.OPTIONAL_ENDTAG))return}else for(f=d.length;0<=--f&&d[f].orig!==a;);if(!(0>f)){for(var m=d.length;--m>f;){var k=d[m].rep;b.ELEMENTS[k]&b.eflags.OPTIONAL_ENDTAG||c.push("</",k,">")}f<d.length&&(a=d[f].rep);d.length=f;c.push("</",a,">")}}}},pcdata:c,rcdata:c,cdata:c,endDoc:function(b){for(;d.length;d.length--)b.push("</",d[d.length-1].rep,">")}})}function D(b,a,c,d,e){if(!e)return null;try{var f=Ma.parse(""+b);if(f&&(!f.hasScheme()||Va.test(f.getScheme()))){var g=e(f,a,c,d);return g?g.toString():
null}}catch(gb){}return null}function z(b,a,c,d,e){c||b(a+" removed",{change:"removed",tagName:a});if(d!==e){var f="changed";d&&!e?f="removed":!d&&e&&(f="added");b(a+"."+c+" "+f,{change:f,tagName:a,attribName:c,oldValue:d,newValue:e})}}function E(b,a,c){var d;d=a+"::"+c;if(b.hasOwnProperty(d))return b[d];d="*::"+c;if(b.hasOwnProperty(d))return b[d]}function aa(a,c){return E(b.ATTRIBS,a,c)}function qa(a,c){return E(b.LOADERTYPES,a,c)}function ba(a,c){return E(b.URIEFFECTS,a,c)}function ca(a,c,d,e,
f){for(var g=0;g<c.length;g+=2){var k=c[g],h=c[g+1],n=h,l=null,m;if((m=a+"::"+k,b.ATTRIBS.hasOwnProperty(m))||(m="*::"+k,b.ATTRIBS.hasOwnProperty(m)))l=b.ATTRIBS[m];if(null!==l)switch(l){case b.atype.NONE:break;case b.atype.SCRIPT:h=null;f&&z(f,a,k,n,h);break;case b.atype.STYLE:if("undefined"===typeof fa){h=null;f&&z(f,a,k,n,h);break}var p=[];fa(h,{declaration:function(a,c){var e=a.toLowerCase();ga(e,c,d?function(a){return D(a,b.ueffects.SAME_DOCUMENT,b.ltypes.SANDBOXED,{TYPE:"CSS",CSS_PROP:e},d)}:
null);c.length&&p.push(e+": "+c.join(" "))}});h=0<p.length?p.join(" ; "):null;f&&z(f,a,k,n,h);break;case b.atype.ID:case b.atype.IDREF:case b.atype.IDREFS:case b.atype.GLOBAL_NAME:case b.atype.LOCAL_NAME:case b.atype.CLASSES:h=e?e(h):h;f&&z(f,a,k,n,h);break;case b.atype.URI:h=D(h,ba(a,k),qa(a,k),{TYPE:"MARKUP",XML_ATTR:k,XML_TAG:a},d);f&&z(f,a,k,n,h);break;case b.atype.URI_FRAGMENT:h&&"#"===h.charAt(0)?(h=h.substring(1),h=e?e(h):h,null!==h&&void 0!==h&&(h="#"+h)):h=null;f&&z(f,a,k,n,h);break;default:h=
null,f&&z(f,a,k,n,h)}else h=null,f&&z(f,a,k,n,h);c[g+1]=h}return c}function ha(a,c,d){return function(e,f){if(b.ELEMENTS[e]&b.eflags.UNSAFE)d&&z(d,e,void 0,void 0,void 0);else return{attribs:ca(e,f,a,c,d)}}}function R(b,a){var c=[];r(a)(b,c);return c.join("")}function V(b,a,c,d){a=ha(a,c,d);return R(b,a)}var fa,ga,za;"undefined"!==typeof window&&(fa=window.parseCssDeclarations,ga=window.sanitizeCssProperty,za=window.cssSchema);var da={lt:"<",LT:"<",gt:">",GT:">",amp:"&",AMP:"&",quot:'"',apos:"'",
nbsp:"\u00a0"},va=/^#(\d+)$/,wa=/^#x([0-9A-Fa-f]+)$/,O=/^[A-Za-z][A-Za-z0-9]+$/,ea="undefined"!==typeof window&&window.document?window.document.createElement("textarea"):null,P=/\0/g,K=/&(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/g,U=/^(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/,n=/&/g,l=/&([^a-z#]|#(?:[^0-9x]|x(?:[^0-9a-f]|$)|$)|$)/gi,B=/[<]/g,F=/>/g,Q=/\"/g,I=/^\s*(\[[-.:\w]+\]|[-.:\w]+)(?:\s*(=)\s*((")[^"]*("|$)|(')[^']*('|$)|(?=[a-z][-\w]*\s*=)|[^"'\s]*))?/i,ra=3==="a,b".split(/(,)/).length,xa=b.eflags.CDATA|b.eflags.RCDATA,
y={},sa={},Va=/^(?:https?|geo|mailto|sms|tel)$/i,x={};x.escapeAttrib=x.escapeAttrib=f;x.makeHtmlSanitizer=x.makeHtmlSanitizer=r;x.makeSaxParser=x.makeSaxParser=p;x.makeTagPolicy=x.makeTagPolicy=ha;x.normalizeRCData=x.normalizeRCData=h;x.sanitize=x.sanitize=V;x.sanitizeAttribs=x.sanitizeAttribs=ca;x.sanitizeWithPolicy=x.sanitizeWithPolicy=R;x.unescapeEntities=x.unescapeEntities=d;return x}(Z);var Oa=M({applet:!0,audio:!0,base:!0,embed:!0,frame:!0,frameset:!0,iframe:!0,img:!0,link:!0,meta:!0,object:!0,script:!0,style:!0,svg:!0,video:!0}),Pa=M({br:!0,col:!0,hr:!0,img:!0,input:!0,source:!0,track:!0,wbr:!0,area:!0,base:!0,command:!0,embed:!0,keygen:!0,link:!0,meta:!0,param:!0}),Qa="b br code del em i ins mark q s small strong sub sup time u".split(" "),Ra="fallback on option placeholder submit-success submit-error href style text subscriptions-action subscriptions-actions subscriptions-section subscriptions-display".split(" "),
Sa=M({a:["rel"],div:["template"],form:["action-xhr","custom-validation-reporting","target"],template:["type"]}),Ta=/^(data-|aria-)|^role$/i,Ua=["_top","_blank"],Wa=["javascript:","vbscript:","data:","<script","\x3c/script"],Xa=M({input:{type:/(?:image|file|password|button)/i}}),Ya="form formaction formmethod formtarget formnovalidate formenctype".split(" "),Za=M({input:Ya,textarea:Ya,select:Ya}),$a=/!important|position\s*:\s*fixed|position\s*:\s*sticky/i;
function ab(b){function a(b){0==d&&e.push(b)}var c=Na.makeTagPolicy(),e=[],d=0,f=Na.makeSaxParser({startTag:function(b,e){if(0<d)Pa[b]||d++;else{for(var f=Object.create(null),k=0;k<e.length;k+=2){var h=e[k];h&&"["==h[0]&&"]"==h[h.length-1]&&(f[k]=!0,e[k]=h.slice(1,-1))}if(Oa[b])d++;else if(!N(b,"amp-")){var p=e.slice(0),A=c(b,e);if(A)for(e=A.attribs,k=0;k<e.length;k+=2){var w=e[k];Ra.includes(w)?e[k+1]=p[k+1]:0==w.search(Ta)?e[k+1]=p[k+1]:Sa[b]&&Sa[b].includes(w)&&(e[k+1]=p[k+1])}else d++;if("a"==
b){for(var k=-1,u=!1,h=0;h<p.length;h+=2)"target"==p[h]?k=h+1:"href"==p[h]&&(u=null!=e[h+1]);var C=-1!=k?p[k]:null;null!=C?(C=C.toLowerCase(),-1!=Ua.indexOf(C)?e[k]=C:e[k]="_top"):u&&(e.push("target"),e.push("_top"))}}if(0<d)Pa[b]&&d--;else{a("<");a(b);for(k=0;k<e.length;k+=2){var r=e[k],D=e[k+1];if(bb(b,r,D)){a(" ");f[k]?a("["+r+"]"):a(r);a('="');if(D){if(f[k])h=D;else var h=D,z=b.toLowerCase(),E=r.toLowerCase(),h="src"==E||"href"==E||"srcset"==E?cb(z,E,h):h;var aa=h;a(Na.escapeAttrib(aa))}a('"')}else J().error("sanitizer",
'Removing "'+r+'" attribute with invalid '+("value in <"+b+" "+r+'="'+D+'">.'))}a(">")}}},endTag:function(b){0<d?d--:(a("</"),a(b),a(">"))},pcdata:a,rcdata:a,cdata:a});f(b);return e.join("")}
function bb(b,a,c){if(N(a,"on")&&"on"!=a)return!1;if("style"==a){a=self;if(a.__AMP__EXPERIMENT_TOGGLES)b=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);b=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var e in a.AMP_CONFIG){var d=a.AMP_CONFIG[e];"number"===typeof d&&0<=d&&1>=d&&(b[e]=Math.random()<d)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(e=a.AMP_CONFIG["allow-doc-opt-in"],d=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var d=
d.getAttribute("content").split(","),f=0;f<d.length;f++)-1!=e.indexOf(d[f])&&(b[d[f]]=!0);Object.assign(b,Ha(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length)for(e=a.AMP_CONFIG["allow-url-opt-in"],a=ka(a.location.originalHash||a.location.hash),d=0;d<e.length;d++)f=a["e-"+e[d]],"1"==f&&(b[e[d]]=!0),"0"==f&&(b[e[d]]=!1)}return b["inline-styles"]?!$a.test(c):!1}if("class"==a&&c&&/(^|\W)i-amphtml-/i.test(c))return!1;if(c){var h=c.toLowerCase().replace(/[\s,\u0000]+/g,
"");for(e=0;e<Wa.length;e++)if(-1!=h.indexOf(Wa[e]))return!1}var p=Za[b];if(p&&-1!=p.indexOf(a))return!1;var g=Xa[b];if(g){var k=g[a];if(k&&-1!=c.search(k))return!1}return!0}function cb(b,a,c){var e=self.location;Ea(c);var d=Ba(e),f=X(Ca(e));if("href"==a&&!N(c,"#"))return Da(c,f);if("src"==a)return"amp-img"==b?db(c,f,d):Da(c,f);if("srcset"==a){var h;try{h=Ja(c)}catch(p){return J().error("sanitizer","Failed to parse srcset: ",p),c}return h.stringify(function(b){return db(b,f,d)})}return c}
function db(b,a,c){b=X(Da(b,a));return"data:"==b.protocol||Ba(b)||!c?b.href:ma+"/i/"+("https:"==b.protocol?"s/":"")+encodeURIComponent(b.host)+b.pathname+(b.search||"")+(b.hash||"")};/*
 mustache.js - Logic-less {{mustache}} templates with JavaScript
 http://github.com/janl/mustache.js
*/
var eb={};
(function mustacheFactory(a){function c(a){return"function"===typeof a}function e(a){return r(a)?"array":typeof a}function d(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&")}function f(a,c){return null!=a&&"object"===typeof a&&Object.prototype.hasOwnProperty.call(a,c)}function h(a,c){return D.call(a,c)}function p(a){return!h(z,a)}function g(a){return String(a).replace(/[&<>"'`=\/]/g,function ga(a){return E[a]})}function k(c,e){function f(){if(O&&!w)for(;u.length;)delete k[u.pop()];else u=
[];w=O=!1}function g(a){"string"===typeof a&&(a=a.split(qa,2));if(!r(a)||2!==a.length)throw Error("Invalid tags: "+a);P=new RegExp(d(a[0])+"\\s*");K=new RegExp("\\s*"+d(a[1]));U=new RegExp("\\s*"+d("}"+a[1]))}if(!c)return[];var h=[],k=[],u=[],O=!1,w=!1,P,K,U;g(e||a.tags);for(var n=new A(c),l,B,F,Q,I;!n.eos();){c=n.pos;if(B=n.scanUntil(P)){l=0;for(var ra=B.length;l<ra;++l)F=B.charAt(l),p(F)?u.push(k.length):w=!0,k.push(["text",F,c,c+1]),c+=1,"\n"===F&&f()}if(!n.scan(P))break;O=!0;l=n.scan(ha)||"name";
n.scan(aa);"="===l?(B=n.scanUntil(ba),n.scan(ba),n.scanUntil(K)):"{"===l?(B=n.scanUntil(U),n.scan(ca),n.scanUntil(K),l="&"):B=n.scanUntil(K);if(!n.scan(K))throw Error("Unclosed tag at "+n.pos);Q=[l,B,c,n.pos];k.push(Q);if("#"===l||"^"===l)h.push(Q);else if("/"===l){I=h.pop();if(!I)throw Error('Unopened section "'+B+'" at '+c);if(I[1]!==B)throw Error('Unclosed section "'+I[1]+'" at '+c);}else if("name"===l||"{"===l||"&"===l)w=!0}if(I=h.pop())throw Error('Unclosed section "'+I[1]+'" at '+n.pos);return S(T(k))}
function T(a){for(var c=[],d,e,f=0,g=a.length;f<g;++f)if(d=a[f])"text"===d[0]&&e&&"text"===e[0]?(e[1]+=d[1],e[3]=d[3]):(c.push(d),e=d);return c}function S(a){for(var c=[],d=c,e=[],f,g,h=0,k=a.length;h<k;++h)switch(f=a[h],f[0]){case "#":case "^":d.push(f);e.push(f);d=f[4]=[];break;case "/":g=e.pop();g[5]=f[2];d=0<e.length?e[e.length-1][4]:c;break;default:d.push(f)}return c}function A(a){this.tail=this.string=a;this.pos=0}function w(a,c){this.view=a;this.cache={".":this.view};this.parent=c}function u(){this.cache=
{}}var C=Object.prototype.toString,r=Array.isArray||function fa(a){return"[object Array]"===C.call(a)},D=RegExp.prototype.test,z=/\S/,E={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;","`":"&#x60;","=":"&#x3D;"},aa=/\s*/,qa=/\s+/,ba=/\s*=/,ca=/\s*\}/,ha=/#|\^|\/|>|\{|&|=|!/;A.prototype.eos=function ga(){return""===this.tail};A.prototype.scan=function za(a){a=this.tail.match(a);if(!a||0!==a.index)return"";a=a[0];this.tail=this.tail.substring(a.length);this.pos+=a.length;return a};
A.prototype.scanUntil=function da(a){a=this.tail.search(a);var c;switch(a){case -1:c=this.tail;this.tail="";break;case 0:c="";break;default:c=this.tail.substring(0,a),this.tail=this.tail.substring(a)}this.pos+=c.length;return c};w.prototype.push=function va(a){return new w(a,this)};w.prototype.lookup=function wa(a){var d=this.cache,e;if(d.hasOwnProperty(a))e=d[a];else{for(var g=this,h,k,l=!1;g;){if(0<a.indexOf("."))for(e=g.view,h=a.split("."),k=0;null!=e&&k<h.length;){if(!f(e,h[k])){e=null;break}k===
h.length-1&&(l=!0);e=e[h[k++]]}else f(g.view,a)?(e=g.view[a],l=!0):e=null;if(l)break;g=g.parent}d[a]=e}c(e)&&(e=e.call(this.view));return e};u.prototype.clearCache=function O(){this.cache={}};u.prototype.parse=function(a,c){var d=this.cache,e=d[a];null==e&&(e=d[a]=k(a,c));return e};u.prototype.render=function ea(a,c,d){var e=this.parse(a);c=c instanceof w?c:new w(c);return this.renderTokens(e,c,d,a)};u.prototype.renderTokens=function P(a,c,d,e){for(var f="",g,h,k,l=0,n=a.length;l<n;++l)k=void 0,g=
a[l],h=g[0],"#"===h?k=this.renderSection(g,c,d,e):"^"===h?k=this.renderInverted(g,c,d,e):">"===h?k=this.renderPartial(g,c,d,e):"&"===h?k=this.unescapedValue(g,c):"name"===h?k=this.escapedValue(g,c):"text"===h&&(k=this.rawValue(g)),void 0!==k&&(f+=k);return f};u.prototype.renderSection=function K(a,d,e,f){function g(a){return h.render(a,d,e)}var h=this,k="",l=d.lookup(a[1]);if(l){if(r(l))for(var n=0,p=l.length;n<p;++n)k+=this.renderTokens(a[4],d.push(l[n]),e,f);else if("object"===typeof l||"string"===
typeof l||"number"===typeof l)k+=this.renderTokens(a[4],d.push(l),e,f);else if(c(l)){if("string"!==typeof f)throw Error("Cannot use higher-order sections without the original template");l=l.call(d.view,f.slice(a[3],a[5]),g);null!=l&&(k+=l)}else k+=this.renderTokens(a[4],d,e,f);return k}};u.prototype.renderInverted=function U(a,c,d,e){var f=c.lookup(a[1]);if(!f||r(f)&&0===f.length)return this.renderTokens(a[4],c,d,e)};u.prototype.renderPartial=function n(a,d,e){if(e&&(a=c(e)?e(a[1]):e[a[1]],null!=
a))return this.renderTokens(this.parse(a),d,e,a)};u.prototype.unescapedValue=function l(c,d){c=d.lookup(c[1]);if(null!=c)return a.sanitizeUnescaped?a.sanitizeUnescaped(c):c};u.prototype.escapedValue=function B(c,d){c=d.lookup(c[1]);if(null!=c)return a.escape(c)};u.prototype.rawValue=function F(a){return a[1]};a.name="mustache.js";a.version="2.2.0";a.tags=["{{","}}"];var R=new u;a.clearCache=function(){return R.clearCache()};a.parse=function(a,c){return R.parse(a,c)};a.render=function(a,c,d){if("string"!==
typeof a)throw new TypeError('Invalid template! Template should be a "string" but "'+e(a)+'" was given as the first argument for mustache#render(template, view, partials)');return R.render(a,c,d)};a.to_html=function Q(d,e,f,g){var h=a.render(d,e,f);if(c(g))g(h);else return h};a.escape=g;a.sanitizeUnescaped=null;a.setUnescapedSanitizier=function I(c){a.sanitizeUnescaped=c};a.Scanner=A;a.Context=w;a.Writer=u})(eb);eb.setUnescapedSanitizier(function(b){return Na.sanitizeWithPolicy(b,function(a,b){if("template"==a)for(var c=0;c<b.length;c+=2)if("type"==b[c]&&"amp-mustache"==b[c+1])return{tagName:a,attribs:["type","amp-mustache"]};return Qa.includes(a)?{tagName:a,attribs:[]}:null})});function fb(b){return AMP.BaseTemplate.apply(this,arguments)||this}ia(fb,AMP.BaseTemplate);
fb.prototype.compileCallback=function(){var b=this;this.G={};var a=0,c=Fa(this.element);Ga(c.querySelectorAll("template"),function(c){var d="__AMP_NESTED_TEMPLATE_"+a;b.G[d]=c.outerHTML;var e=b.element.ownerDocument.createTextNode("{{{"+d+"}}}");c.parentNode.replaceChild(e,c);a++});var e=this.element.ownerDocument.createElement("div");e.appendChild(c);this.H=e.innerHTML;eb.parse(this.H)};
fb.prototype.render=function(b){var a=b;"object"===typeof b&&(a=Object.assign({},b,this.G));b=eb.render(this.H,a);var c=ab(b);b=this.win.document.createElement("div");b.innerHTML=c;return this.unwrap(b)};AMP.registerTemplate("amp-mustache",fb);
})});
//# sourceMappingURL=amp-mustache-0.1.js.map

