(self.AMP=self.AMP||[]).push({n:"amp-youtube",v:"1522422854768",f:(function(AMP){var h;(function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a})(this);function aa(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,d);f&&Object.defineProperty(a,d,f)}else a[d]=b[d]}function ba(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ca=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function da(a){var b=Object.create(null);if(!a)return b;for(var c;c=ca.exec(a);){var d=ba(c[1],c[1]),f=c[2]?ba(c[2],c[2]):"";b[d]=f}return b};var m="";function ea(a){var b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;var d=da(c.location.originalHash||c.location.hash),f=da(c.location.search);m||(m=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011522422854768");c=b.AMP_MODE={localDev:!1,development:!("1"!=d.development&&!c.AMP_DEV_MODE),examiner:"2"==d.development,filter:d.filter,minified:!0,lite:void 0!=f.amp_lite,test:!1,log:d.log,version:"1522422854768",rtvVersion:m}}return c};var fa=Object.prototype.toString;function n(a){return"[object Object]"===fa.call(a)}function r(a){return"number"===typeof a&&isFinite(a)};self.log=self.log||{user:null,dev:null,userForEmbed:null};var t=self.log;function ga(){if(!t.user)throw Error("failed to call initLogConstructor");return t.user}function u(){if(t.dev)return t.dev;throw Error("failed to call initLogConstructor");};function ha(a){var b=Object.create(null);a&&Object.assign(b,a);return b}function v(a){return a||{}};function w(a){this.Oa=a;this.M=Object.create(null)}w.prototype.get=function(a){if(this.M[a])return this.M[a].access=Date.now(),this.M[a].payload};w.prototype.put=function(a,b){var c=this;this.M[a]={payload:b,access:Date.now()};var d=Object.keys(this.M);d.length>this.Oa&&(u().warn("lru-cache","Trimming template cache"),d.sort(function(a,b){return c.M[b].access-c.M[a].access}),delete this.M[d[d.length-1]])};function x(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};v({c:!0,v:!0,a:!0,ad:!0});var y,z,ia=["javascript:","data:","vbscript:"];
function ja(a){if(!a)return!0;if("string"==typeof a){y||(y=self.document.createElement("a"),z=self.UrlCache||(self.UrlCache=new w(100)));var b=z.get(a);if(b)a=b;else{b=y;b.href=a;b.protocol||(b.href=b.href);var c={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:"0"==b.port?"":b.port,pathname:b.pathname,search:b.search,hash:b.hash,origin:null};"/"!==c.pathname[0]&&(c.pathname="/"+c.pathname);if("http:"==c.protocol&&80==c.port||"https:"==c.protocol&&443==c.port)c.port="",c.host=
c.hostname;c.origin=b.origin&&"null"!=b.origin?b.origin:"data:"!=c.protocol&&c.host?c.protocol+"//"+c.host:c.href;z.put(a,c);a=c}}return!ia.includes(a.protocol)};function ka(a){var b;try{return JSON.parse(a)}catch(c){b&&b(c)}};function la(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView;if(b=b!=(b.__AMP_TOP||b)&&ma(b,"action")?A(b,"action"):null)return b}return B(a,"action")}function na(a,b,c){var d=C(a),f=oa(d);a=f;var g=pa(a),e=g[b];e||(e=g[b]={obj:null,promise:null,resolve:null,context:null,ctor:null});e.ctor||e.obj||(e.ctor=c,e.context=d,e.resolve&&A(a,b))}function D(a,b){a=a.__AMP_TOP||a;return A(a,b)}function B(a,b){a=C(a);a=oa(a);return A(a,b)}
function C(a){return a.nodeType?D((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function oa(a){a=C(a);return a.isSingleDoc()?a.win:a}function A(a,b){ma(a,b);var c=pa(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function pa(a){var b=a.services;b||(b=a.services={});return b}function ma(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function E(a){a.parentElement&&a.parentElement.removeChild(a)}function qa(a){var b,c,d=b||function(a){return a},f=a.dataset;a={};var g=c?c:/^param(.+)/,e;for(e in f){var k=e.match(g);if(k){var l=k[1][0].toLowerCase()+k[1].substr(1);a[d(l)]=f[e]}}return a}function ra(a){var b=a.body.getAttribute("dir")||a.documentElement.getAttribute("dir")||"ltr";return"rtl"==b};function F(a){return B(a,"viewport")};var G,sa="Webkit webkit Moz moz ms O o".split(" ");function ta(a,b){var c=void 0;if(x(b,"--"))return b;G||(G=ha());var d=G[b];if(!d||c){d=b;if(void 0===a[b]){var f=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var g=0;g<sa.length;g++){var e=sa[g]+f;if(void 0!==a[e]){f=e;break a}}f=""}var k=f;void 0!==a[k]&&(d=k)}c||(G[b]=d)}return d}function ua(a,b,c){var d;(b=ta(a.style,b))&&(a.style[b]=d?c+d:c)}function H(a,b){for(var c in b)ua(a,c,b[c])}
function va(a,b){"number"==typeof a&&(a+="px");if(void 0===b)return"translate("+a+")";"number"==typeof b&&(b+="px");return"translate("+a+", "+b+")"};var I;function J(a,b,c){function d(a){try{return e(a)}catch(q){throw self.reportError(q),q;}}var f=void 0,g=a,e=c,k=wa(),l=!1;f&&(l=f.capture);g.addEventListener(b,d,k?f:l);return function(){g&&g.removeEventListener(b,d,k?f:l);d=g=e=null}}function wa(){if(void 0!==I)return I;I=!1;try{var a={get capture(){I=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return I};function K(a,b,c){return J(a,b,c)}function xa(a,b){var c=b,d=J(a,"load",function(a){try{c(a)}finally{c=null,d()}});return d}function ya(a){var b,c,d=new Promise(function(b){c=xa(a,b)});d.then(c,c);b&&b(c);return d};function za(){this.H=null}h=za.prototype;h.add=function(a){var b=this;this.H||(this.H=[]);this.H.push(a);return function(){b.remove(a)}};h.remove=function(a){this.H&&(a=this.H.indexOf(a),-1<a&&this.H.splice(a,1))};h.removeAll=function(){this.H&&(this.H.length=0)};h.fire=function(a){if(this.H)for(var b=this.H,c=0;c<b.length;c++)(0,b[c])(a)};h.getHandlerCount=function(){return this.H?this.H.length:0};function L(a,b,c,d){return{left:a,top:b,width:c,height:d,bottom:b+d,right:a+c,x:a,y:b}}function Aa(a,b){return a&&b?a.left==b.left&&a.top==b.top&&a.width==b.width&&a.height==b.height:!1};function Ba(a,b){function c(){d=0;var e=500-(a.Date.now()-f);if(0<e)d=a.setTimeout(c,e);else{var k=g;g=null;b.apply(null,k)}}var d=0,f=0,g=null;return function(b){for(var e=[],l=0;l<arguments.length;++l)e[l-0]=arguments[l];f=a.Date.now();g=e;d||(d=a.setTimeout(c,500))}};function Ca(a,b,c,d,f){var g=c,e=b;b>c&&(g=b,e=c);a<e?a=e:a>g&&(a=g);return(a-b)*(f-d)/(c-b)+d};function M(a,b,c,d){var f=new Da(0,0,a,b,c,d,1,1);return f.solveYValueFromXValue.bind(f)}function Da(a,b,c,d,f,g,e,k){this.x0=a;this.y0=b;this.x1=c;this.y1=d;this.x2=f;this.y2=g;this.x3=e;this.y3=k}h=Da.prototype;h.solveYValueFromXValue=function(a){return this.getPointY(this.solvePositionFromXValue(a))};
h.solvePositionFromXValue=function(a){var b=1E-6,c=(a-this.x0)/(this.x3-this.x0);if(0>=c)return 0;if(1<=c)return 1;for(var d=0,f=1,g=0,e=0;8>e;e++){var g=this.getPointX(c),k=(this.getPointX(c+b)-g)/b;if(Math.abs(g-a)<b)return c;if(Math.abs(k)<b)break;else g<a?d=c:f=c,c-=(g-a)/k}for(e=0;Math.abs(g-a)>b&&8>e;e++)g<a?(d=c,c=(c+f)/2):(f=c,c=(c+d)/2),g=this.getPointX(c);return c};
h.getPointX=function(a){if(0==a)return this.x0;if(1==a)return this.x3;var b=this.lerp(this.x0,this.x1,a),c=this.lerp(this.x1,this.x2,a),d=this.lerp(this.x2,this.x3,a),b=this.lerp(b,c,a),c=this.lerp(c,d,a);return this.lerp(b,c,a)};h.getPointY=function(a){if(0==a)return this.y0;if(1==a)return this.y3;var b=this.lerp(this.y0,this.y1,a),c=this.lerp(this.y1,this.y2,a),d=this.lerp(this.y2,this.y3,a),b=this.lerp(b,c,a),c=this.lerp(c,d,a);return this.lerp(b,c,a)};h.lerp=function(a,b,c){return a+c*(b-a)};
var Ea=M(.25,.1,.25,1),Fa=M(.42,0,1,1),Ga=M(0,0,.58,1),Ha=M(.42,0,.58,1),Ia={linear:function(a){return a},ease:Ea,"ease-in":Fa,"ease-out":Ga,"ease-in-out":Ha};function Ja(a){if(!a)return null;if("string"==typeof a){if(-1!=a.indexOf("cubic-bezier")){var b=a.match(/cubic-bezier\((.+)\)/);if(b&&(b=b[1].split(",").map(parseFloat),4==b.length)){for(var c=0;4>c;c++)if(isNaN(b[c]))return null;return M(b[0],b[1],b[2],b[3])}return null}return Ia[a]}return a};function Ka(){}function N(a,b){this.W=a;this.o=b||D(self,"vsync");this.za=null;this.F=[]}function La(a,b){var c;return(new N(a)).setCurve(c).add(0,b,1).start(200)}N.prototype.setCurve=function(a){a&&(this.za=Ja(a));return this};N.prototype.add=function(a,b,c,d){this.F.push({delay:a,func:b,duration:c,curve:Ja(d)});return this};
N.prototype.start=function(a){var b=new O(this.o,this.W,this.F,this.za,a);a=b;a.Ga=Date.now();a.fa=!0;a.o.canAnimate(a.W)?a.Ia(a.Ha):(u().warn("Animation","cannot animate"),P(a,!1,0));return b};
function O(a,b,c,d,f){var g=this;this.o=a;this.W=b;this.F=[];for(b=0;b<c.length;b++){var e=c[b];this.F.push({delay:e.delay,func:e.func,duration:e.duration,curve:e.curve||d,started:!1,completed:!1})}this.Pa=f;this.Wa=this.Va=this.Ga=0;this.fa=!1;this.Ha={};this.Da=new Promise(function(a,b){g.Sa=a;g.Ra=b});this.Ia=this.o.createAnimTask(this.W,{mutate:this.Ta.bind(this)})}O.prototype.then=function(a,b){return a||b?this.Da.then(a,b):this.Da};
O.prototype.thenAlways=function(a){a=a||Ka;return this.then(a,a)};O.prototype.halt=function(a){P(this,!1,a||0)};function P(a,b,c){if(a.fa){a.fa=!1;if(0!=c){1<a.F.length&&a.F.sort(function(a,b){return a.delay+a.duration-(b.delay+b.duration)});try{if(0<c)for(c=0;c<a.F.length;c++)a.F[c].func(1,!0);else for(var d=a.F.length-1;0<=d;d--)a.F[d].func(0,!1)}catch(f){u().error("Animation","completion failed: "+f,f),b=!1}}b?a.Sa():a.Ra()}}
O.prototype.Ta=function(){if(this.fa){for(var a=Date.now(),b=Math.min((a-this.Ga)/this.Pa,1),c=0;c<this.F.length;c++){var d=this.F[c];!d.started&&b>=d.delay&&(d.started=!0)}for(c=0;c<this.F.length;c++)if(d=this.F[c],d.started&&!d.completed)a:{var f,g;if(0<d.duration){if(f=g=Math.min((b-d.delay)/d.duration,1),d.curve&&1!=f)try{f=d.curve(g)}catch(e){u().error("Animation","step curve failed: "+e,e);P(this,!1,0);break a}}else f=g=1;1==g&&(d.completed=!0);try{d.func(f,d.completed)}catch(e){u().error("Animation",
"step mutate failed: "+e,e),P(this,!1,0)}}1==b?P(this,!0,0):this.o.canAnimate(this.W)?this.Ia(this.Ha):(u().warn("Animation","cancel animation"),P(this,!1,0))}};function Ma(a){var b;b=void 0===b?" ":b;return function(c,d){for(var f=[],g=0;g<a.length;g++){var e=(0,a[g])(c,d);"string"==typeof e&&f.push(e)}return f.join(b)}}function Na(a,b){return function(c,d){for(var f in b)ua(a,f,b[f](c,d))}}function Q(a,b){return function(c){return a+(b-a)*c}}function Oa(a){return function(b){return a(b)+"px"}}
function Pa(a,b){return function(c){var d=a(c);"number"==typeof d&&(d+="px");if(!b)return"translate("+d+")";c=b(c);"number"==typeof c&&(c+="px");return"translate("+d+","+c+")"}}function Qa(){var a=Q(.6,.6);return function(b){return"scale("+a(b)+")"}};var Ra={title:"",artist:"",album:"",artwork:[{src:""}]};function Sa(a,b,c,d){var f=a.navigator;"mediaSession"in f&&a.MediaMetadata&&(f.mediaSession.metadata=new a.MediaMetadata(Ra),Ta(b),f.mediaSession.metadata=new a.MediaMetadata(b),f.mediaSession.setActionHandler("play",c),f.mediaSession.setActionHandler("pause",d))}
function Ua(a){var b=a.querySelector('script[type="application/ld+json"]');if(b){var c=ka(b.textContent);if(c&&c.image){if("string"===typeof c.image)return c.image;if(c.image["@list"]&&"string"===typeof c.image["@list"][0])return c.image["@list"][0];if("string"===typeof c.image.url)return c.image.url;if("string"===typeof c.image[0])return c.image[0]}}}function Ta(a){a&&a.artwork&&(Array.isArray(a.artwork),a.artwork.forEach(function(a){if(a){var b=n(a)?a.src:a;ga().assert(ja(b))}}))};function R(){this.ba=!1;this.Aa=new za}R.prototype.onSessionEnd=function(a){this.Aa.add(a)};R.prototype.beginSession=function(){this.ba=!0};R.prototype.endSession=function(){this.ba&&this.Aa.fire();this.ba=!1};R.prototype.isSessionActive=function(){return this.ba};function Va(a,b,c,d){this.element=b;this.Ba=d;this.fidelity=c;this.turn=0==c?Math.floor(4*Math.random()):0;this.ea=null;this.l=F(a)}
Va.prototype.update=function(a){var b=this;if(!a){if(0!=this.turn){this.turn--;return}0==this.fidelity&&(this.turn=4)}var c=this.l.getSize(),d=L(0,0,c.width,c.height);this.l.getClientRectAsync(this.element).then(function(a){var c={positionRect:a,viewportRect:d,relativePos:""},e=b.ea;if(!(e&&Aa(e.positionRect,c.positionRect)&&Aa(e.viewportRect,c.viewportRect))){var e=c.positionRect,f=c.viewportRect;c.relativePos=e.top<f.top?"top":e.bottom>f.bottom?"bottom":"inside";f=c.viewportRect;e.top<=f.bottom&&
f.top<=e.bottom&&e.left<=f.right&&f.left<=e.right?(b.ea=c,b.Ba(c)):b.ea&&(b.ea=null,c.positionRect=null,b.Ba(c))}})};function S(a){var b=this;this.w=a;this.Ka=a.win;this.P=[];this.o=D(this.Ka,"vsync");this.l=F(a);this.ga=[];this.ka=this.ra=this.oa=!1;this.Na=Ba(this.Ka,function(){b.oa=!1})}S.prototype.observe=function(a,b,c){var d=new Va(this.w,a,b,c);this.P.push(d);this.ka||Wa(this);d.update()};S.prototype.unobserve=function(a){for(var b=0;b<this.P.length;b++)if(this.P[b].element==a){this.P.splice(b,1);if(0==this.P.length)for(this.ka=!1;this.ga.length;)this.ga.pop()();return}u().error("POSITION_OBSERVER","cannot unobserve unobserved element")};
function Wa(a){a.ka=!0;a.ga.push(a.l.onScroll(function(){a.Na();a.oa=!0;a.ra||Xa(a)}));a.ga.push(a.l.onResize(function(){a.updateAllEntries(!0)}))}S.prototype.updateAllEntries=function(a){for(var b=0;b<this.P.length;b++)this.P[b].update(a)};function Xa(a){a.updateAllEntries();a.ra=!0;a.oa?a.o.measure(function(){Xa(a)}):a.ra=!1}function Ya(a){na(a,"position-observer",function(){return new S(a)})};function Za(a){var b=this;this.ampdoc=a;this.l=F(this.ampdoc);this.B=null;this.Ea=this.Fa=!1;this.aa=this.va=null;this.Ja=D(a.win,"timer");this.La=la(a);this.ya=function(){for(var a=0;a<b.B.length;a++){var d=b.B[a];if("paused"!==d.getPlayingState()){T(d,"video-seconds-played");var f,g=d.video.getCurrentTime(),e=d.video.getDuration();r(g)&&r(e)&&0<e&&(f=b.ampdoc.win,g={time:g,percent:g/e},e={detail:g},Object.assign(e,void 0),"function"==typeof f.CustomEvent?f=new f.CustomEvent("video-manager.timeUpdate",
e):(f=f.document.createEvent("CustomEvent"),f.initCustomEvent("video-manager.timeUpdate",!!e.bubbles,!!e.cancelable,g)),b.La.trigger(d.video.element,"timeUpdate",f,1))}}b.Ja.delay(b.ya,1E3)};this.Ja.delay(this.ya,1E3)}h=Za.prototype;
h.register=function(a,b){b=void 0===b?!0:b;var c=a;c.registerAction("play",c.play.bind(c,!1),1);c.registerAction("pause",c.pause.bind(c),1);c.registerAction("mute",c.mute.bind(c),1);c.registerAction("unmute",c.unmute.bind(c),1);c.registerAction("fullscreen",c.fullscreenEnter.bind(c),1);a.supportsPlatform()&&(this.B=this.B||[],c=new $a(this,a,b),ab(this,c),bb(this,c),cb(this,c),this.B.push(c),a.element.dispatchCustomEvent("registered"),a.element.classList.add("i-amphtml-video-interface"))};
function ab(a,b){K(b.video.element,"amp:video:visibility",function(a){var c=a.data;c&&1==c.visible?b.updateVisibility(!0):b.updateVisibility()});K(b.video.element,"reloaded",function(){b.videoLoaded()});if(!a.Fa){var c=function(){for(var b=0;b<a.B.length;b++)a.B[b].updateVisibility()};a.l.onScroll(c);a.l.onChanged(c);a.Fa=!0}}
function cb(a,b){if(b.hasFullscreenOnLandscape){var c=a.ampdoc.win,d=c.screen,f=function(){var a,f=a=d&&"orientation"in d?x(d.orientation.type,"landscape"):-90==c.orientation||90==c.orientation;b.Z&&(!f&&b.Y?b.Y&&(b.video.fullscreenExit(),b.Y=!1):f&&"playing_manual"==b.getPlayingState()&&b.K&&B(b.w,"viewer").isVisible()&&!b.video.isFullscreen()&&!b.Y&&(b.video.fullscreenEnter(),b.Y=b.video.isFullscreen()))};if(d&&"orientation"in d){var g=d.orientation;K(g,"change",f.bind(a))}K(c,"orientationchange",
f.bind(a))}}function bb(a,b){if(b.hasDocking&&(a.va||(Ya(a.ampdoc),a.va=B(a.ampdoc,"position-observer")),a.va.observe(b.video.element,1,function(a){b.onDockableVideoPositionChanged(a)}),!a.Ea)){var c=function(){for(var b=0;b<a.B.length;b++)a.B[b].refreshDockedVideo()};a.l.onResize(c);a.Ea=!0}}function db(a,b){for(var c=0;c<a.B.length;c++)if(a.B[c].video===b)return a.B[c];u().error("video-manager","video is not registered to this video manager");return null}
h.getVideoAnalyticsDetails=function(a){var b;a:{for(b=0;b<this.B.length;b++){var c=this.B[b];if(c.video.element===a){b=c;break a}}u().error("video-manager","video is not registered to this video manager");b=null}return b?b.getAnalyticsDetails():Promise.resolve()};h.getPlayingState=function(a){return db(this,a).getPlayingState()};h.userInteractedWithAutoPlay=function(a){return db(this,a).userInteractedWithAutoPlay()};h.canDock=function(a){return!this.aa||this.aa==a};
h.registerDocked=function(a){this.aa=a};h.unregisterDocked=function(){this.aa=null;for(var a=0;a<this.B.length;a++)this.B[a].$=!1};
function $a(a,b,c){var d=this;this.qa=a;this.w=a.ampdoc;this.l=F(this.w);this.video=b;this.Ma=c;this.Ua=null;this.Y=this.K=this.S=this.Z=!1;this.o=D(this.w.win,"vsync");this.ia=new R;this.ia.onSessionEnd(function(){return T(d,"video-session")});this.V=new R;this.V.onSessionEnd(function(){return T(d,"video-session-visible")});this.ja=eb.bind(null,this.w.win,ea(this.w.win).lite);b=b.element;this.sa=this.Ca=this.ha=!1;this.I=this.A=null;this.O=!1;this.D=this.j=null;this.G=this.C="inline";this.X=0;this.la=
null;this.pa=this.ca=this.J=this.T=this.ma=this.$=!1;this.h={mouse:{x:0,y:0},displacement:{x:0,y:0},initial:{x:0,y:0},position:{x:0,y:0},previous:{x:0,y:0},velocity:{x:0,y:0}};this.na=[];this.hasDocking=b.hasAttribute("dock");this.hasAutoplay=b.hasAttribute("autoplay");var f=b.getAttribute("fullscreen-on-landscape");this.hasFullscreenOnLandscape=""==f||"always"==f;this.N=Ra;ya(b).then(function(){return d.videoLoaded()});K(b,"pause",function(){T(d,"video-pause");d.S=!1;d.sa?d.sa=!1:d.ia.endSession()});
K(b,"playing",function(){return fb(d)});K(b,"muted",function(){return d.O=!0});K(b,"unmuted",function(){return d.O=!1});K(b,"ended",function(){T(d,"video-ended")});this.updateVisibility();this.hasAutoplay&&gb(this);this.hasDocking&&hb(this)}function fb(a){a.S=!0;a.video.preimplementsMediaSessionAPI()||Sa(a.w.win,a.N,function(){a.video.play(!1)},function(){a.video.pause()});a.ia.beginSession();a.K&&a.V.beginSession();T(a,"video-play")}h=$a.prototype;
h.videoLoaded=function(){var a=this;this.Z=!0;this.A=this.video.element.querySelector("video, iframe");this.o.measure(function(){a.j=a.video.element.getBoundingClientRect()});ib(this);this.updateVisibility();this.K&&jb(this)};
function ib(a){if(!a.video.preimplementsMediaSessionAPI()){a.video.getMetadata()&&(a.N=ha(a.video.getMetadata()));var b=a.w.win.document;if(!a.N.artwork||0==a.N.artwork.length){var c;(c=Ua(b))||(c=(c=b.querySelector('meta[property="og:image"]'))?c.getAttribute("content"):void 0);c||(c=(c=b.querySelector('link[rel="shortcut icon"]')||b.querySelector('link[rel="icon"]'))?c.getAttribute("href"):void 0);var d=c;d&&(a.N.artwork=[{src:d}])}!a.N.title&&(b=a.video.element.getAttribute("title")||a.video.element.getAttribute("aria-label")||
a.A.getAttribute("title")||a.A.getAttribute("aria-label")||b.title)&&(a.N.title=b)}}function jb(a){B(a.w,"viewer").isVisible()&&a.ja().then(function(b){var c=a.hasAutoplay&&!a.ha;c&&b?a.Ma&&(a.K?(a.V.beginSession(),a.video.play(!0),a.Ca=!0):(a.S&&a.V.endSession(),a.video.pause(),a.sa=!0)):a.K?a.V.beginSession():a.S&&a.V.endSession()})}
function gb(a){a.video.isInteractive()&&a.video.hideControls();a.ja().then(function(b){!b&&a.video.isInteractive()?a.video.showControls():(a.video.mute(),a.video.isInteractive()&&kb(a))})}
function kb(a){function b(b){a.o.mutate(function(){g.classList.toggle("amp-video-eq-play",b)})}function c(){this.ha=!0;this.video.showControls();this.video.unmute();k.forEach(function(a){a()});E(g);E(e)}function d(){H(e,{display:"none"})}function f(){H(e,{display:"block"})}a.video.hideControls();var g=lb(a),e=mb(a);a.o.mutate(function(){a.video.element.appendChild(g);a.video.element.appendChild(e)});var k=[];k.push(K(e,"click",c.bind(a)));k.push(K(g,"click",c.bind(a)));k.push(K(a.video.element,"pause",
b.bind(a,!1)));k.push(K(a.video.element,"playing",b.bind(a,!0)));k.push(K(a.video.element,"ad_start",d.bind(a)));k.push(K(a.video.element,"ad_end",f.bind(a)))}function hb(a){a.o.run({measure:function(){a.j=a.video.element.getBoundingClientRect()},mutate:function(){a.video.element.classList.add("i-amphtml-dockable-video")}})}function U(a,b,c,d){return(d=void 0===d?!1:d)?Ca(a.X,a.j.height,0,b,c):Ca(a.X,0,a.j.height,b,c)}
h.refreshDockedVideo=function(){var a=this;this.o.run({measure:function(){a.j=a.video.element.getBoundingClientRect();nb(a)},mutate:function(){a.G="inline";if(a.la)a.onDockableVideoPositionChanged(a.la);ob(a)}})};function nb(a){a.o.measure(function(){a.D=a.A.getBoundingClientRect();a.h.initial.x=a.D.left;a.h.initial.y=a.D.top;a.h.position.x=a.D.left;a.h.position.y=a.D.top;a.h.previous.x=a.D.left;a.h.previous.y=a.D.top;a.h.displacement.x=0;a.h.displacement.y=0})}
function ob(a){a.I&&a.A&&a.o.mutate(function(){function b(a){var b;b=c;b=(a=ta(b.style,a))?b.style[a]:void 0;return b}var c=a.A;H(a.I,{top:b("top"),left:b("left"),bottom:b("bottom"),right:b("right"),transform:b("transform"),"transform-origin":b("transform-origin"),borderRadius:b("borderRadius"),width:b("width"),height:b("height"),position:"fixed","z-index":"17",background:"transparent"})})}
h.onDockableVideoPositionChanged=function(a){var b=this;this.o.run({measure:function(){b.j=b.video.element.getBoundingClientRect();var c="bottom"==a.relativePos,d="top"==a.relativePos,f="inside"==a.relativePos;b.la=a;a.positionRect||(a.positionRect=c?L(b.j.left,b.l.getHeight(),b.j.width,b.j.height):L(b.j.left,-b.j.height,b.j.width,b.j.height));var g=a.viewportRect.top,e=a.viewportRect.bottom,k=a.positionRect.top,l=a.positionRect.bottom;b.X=k<=g?l-g:l>=e?e-k:l-k;b.$=b.$||Math.ceil(b.X)>=b.j.height;
g=b.video.element.offsetTop;e=b.l.getScrollHeight()-g-b.video.element.offsetHeight;c&&g<b.l.getHeight()||d&&e<b.l.getHeight()?b.C="inline":b.video.element.offsetHeight>=b.l.getHeight()?b.C="inline":(g=b.w.win.document,"inline"!=b.C||f)?f&&(b.C="inline"):d?b.C=ra(g)?"top_left":"top_right":c&&(b.C=ra(g)?"bottom_left":"bottom_right")},mutate:function(){if(b.Z&&b.j&&b.A&&("playing_manual"==b.getPlayingState()||b.A.classList.contains("i-amphtml-dockable-video-minimizing"))){var a="inline"!=b.C&&b.$,d=
"playing_manual"==b.getPlayingState(),f="paused"==b.getPlayingState(),g=b.A.classList.contains("i-amphtml-dockable-video-minimizing");if(a&&(d||f&&g)){if("inline"==b.G&&b.qa.canDock(b)&&(b.video.hideControls(),b.A.classList.add("i-amphtml-dockable-video-minimizing"),H(b.A,{height:b.j.height+"px",width:b.j.width+"px",maxWidth:b.j.width+"px"}),H(b.video.element,{"background-color":"#222"}),b.G="docking",b.qa.registerDocked(b)),"inline"!=b.G){var e=b.l.getWidth(),k=b.l.getHeight(),l=e-.6*b.j.width-20,
p=k-.6*b.j.height-20,q=e=0;switch(b.C){case "top_left":e=q=20;break;case "top_right":q=l;e=20;break;case "bottom_left":e=p;q=20;break;case "bottom_right":e=p,q=l}k=Math.max(0,Math.min(k-b.j.height,b.j.top));q=U(b,b.j.left,q,!0)+"px";e=U(b,k,e,!0)+"px";e=va(q,e);k="scale("+U(b,.6,1)+")";H(b.A,{transform:e+" "+k,transformOrigin:"top left",bottom:"auto",top:"0px",right:"auto",left:"0px"});.6==U(b,.6,1)?b.G="docked":b.G="docking"}}else g&&pb(b);"docked"==b.G?qb(b):rb(b)}}})};
function V(a,b,c,d){a.na.push(J(b,c,d))}
function qb(a){a.ma||a.o.run({measure:function(){nb(a)},mutate:function(){a.I=a.w.win.document.createElement("i-amphtml-dragging-mask");ob(a);a.video.element.appendChild(a.I);V(a,a.I,"mousedown",function(b){b.preventDefault();a.T=!0;a.J=!1;W(a,b,!0)});V(a,a.w.win.document,"mouseup",function(){a.T=!1;a.J=!1;X(a)});V(a,a.w.win.document,"mousemove",function(b){a.J=a.T;a.J&&(b.preventDefault(),a.G="draggable",X(a));W(a,b)});V(a,a.I,"touchstart",function(b){b.preventDefault();a.T=!0;a.J=!1;W(a,b,!0)});
V(a,a.w.win.document,"touchend",function(){a.T=!1;a.J=!1;X(a)});V(a,a.w.win.document,"touchmove",function(b){a.J=a.T;a.J&&(b.preventDefault(),a.G="draggable",X(a));W(a,b)});a.ma=!0}})}
function X(a){a.o.run({measure:function(){a.D=a.A.getBoundingClientRect()},mutate:function(){if(a.Z&&a.A&&"inline"!=a.C&&0==a.X&&a.A.classList.contains("i-amphtml-dockable-video-minimizing")&&"draggable"==a.G){var b=a.h;if(a.J){b.previous.x=b.position.x;b.previous.y=b.position.y;b.position.x=b.mouse.x-b.displacement.x;b.position.y=b.mouse.y-b.displacement.y;b.velocity.x=b.position.x-b.previous.x;b.velocity.y=b.position.y-b.previous.y;var c=a.D.width,d=a.D.height,f=b.position.x+c/2,g=b.position.y+
d/2;if(f>a.l.getWidth()||0>f||g>a.l.getHeight()||0>g)a.pa=!0}else if(b.position.x+=b.velocity.x,b.position.y+=b.velocity.y,b.velocity.x*=.55,b.velocity.y*=.55,a.pa){a.video.pause();pb(a);a.pa=!1;return}if(!a.J&&!a.ca&&3>=Math.abs(b.velocity.x)&&3>=Math.abs(b.velocity.y)){var e=a.l.getWidth()-a.D.width-20,k=a.l.getHeight()-a.D.height-20;sb(a);var l=b.position.x,p=b.position.y;switch(a.C){case "bottom_right":l=e;p=k;break;case "top_right":l=e;p=20;break;case "bottom_left":l=20;p=k;break;case "top_left":p=
l=20}if(b.position.x!=l||b.position.y!=p)a.ca=!0,tb(a,a.I,l,p),tb(a,a.A,l,p),a.G="docked"}a.ca||(ub(a,a.I),ub(a,a.A));a.J||a.o.mutate(function(){X(a)})}}})}function rb(a){a.o.mutate(function(){for(var b=a.na.pop();b;)b.call(),b=a.na.pop();a.ma=!1;a.I&&(E(a.I),a.I=null)})}
function W(a,b,c){c=void 0===c?!1:c;b.x?(a.h.mouse.x=b.x,a.h.mouse.y=b.y):b.touches&&(a.h.mouse.x=b.touches[0].clientX,a.h.mouse.y=b.touches[0].clientY);c&&(a.h.displacement.x=Math.abs(a.h.position.x-a.h.mouse.x),a.h.displacement.y=Math.abs(a.h.position.y-a.h.mouse.y))}function sb(a){var b=a.l.getWidth()/2,c=a.l.getHeight()/2,d=a.D.width,f=a.D.height,g=a.h.position.x+d/2,e=a.h.position.y+f/2;g>=b?e>=c?a.C="bottom_right":e<c&&(a.C="top_right"):g<b&&(e>=c?a.C="bottom_left":e<c&&(a.C="top_left"))}
function pb(a){rb(a);a.video.showControls();a.A.classList.remove("i-amphtml-dockable-video-minimizing");a.A.setAttribute("style","");H(a.video.element,{"background-color":"transparent"});a.G="inline";a.qa.unregisterDocked()}
function lb(a){var b=a.w.win.document,c=b.createElement("i-amphtml-video-eq");c.classList.add("amp-video-eq");for(var d=1;4>=d;d++){var f=b.createElement("div");f.classList.add("amp-video-eq-col");for(var g=1;2>=g;g++){var e=b.createElement("div");e.classList.add("amp-video-eq-"+d+"-"+g);f.appendChild(e)}c.appendChild(f)}var k=D(a.w.win,"platform");k.isIos()&&c.setAttribute("unpausable","");return c}
function tb(a,b,c,d){La(b,Na(b,{transform:Ma([Pa(Oa(Q(a.h.position.x,c)),Oa(Q(a.h.position.y,d))),Qa()])})).thenAlways(function(){a.h.position.x=c;a.h.position.y=d;a.ca=!1})}function ub(a,b){a=va(a.h.position.x+"px",a.h.position.y+"px");H(b,{transform:a+" scale(0.6)","transform-origin":"top left",bottom:"auto",top:"0px",right:"auto",left:"0px"})}function mb(a){a=a.w.win.document.createElement("i-amphtml-video-mask");a.classList.add("i-amphtml-fill-content");return a}
h.updateVisibility=function(a){function b(){d.K!=f&&d.Z&&jb(d)}function c(){if(1==a)d.K=!0;else{var b=d.video.element.getIntersectionChangeEntry(),c=r(b.intersectionRatio)?100*b.intersectionRatio:0;d.K=75<=c}}var d=this,f=this.K;this.o.run({measure:c,mutate:b})};h.getPlayingState=function(){return this.S?this.S&&this.Ca&&!this.ha?"playing_auto":"playing_manual":"paused"};h.userInteractedWithAutoPlay=function(){return this.ha};
h.getAnalyticsDetails=function(){var a=this,b=this.video;return this.ja().then(function(c){var d=a.video.element.getLayoutBox(),f=d.width,d=d.height,g=a.hasAutoplay&&c,e=b.getPlayedRanges(),k=e.reduce(function(a,b){return a+b[1]-b[0]},0);return{autoplay:g,currentTime:b.getCurrentTime(),duration:b.getDuration(),height:d,id:b.element.id,muted:a.O,playedTotal:k,playedRangesJson:JSON.stringify(e),state:a.getPlayingState(),width:f}})};var Y=null;
function eb(a,b){if(Y)return Y;if(b)return Y=Promise.resolve(!1);var c=a.document.createElement("video");c.setAttribute("muted","");c.setAttribute("playsinline","");c.setAttribute("webkit-playsinline","");c.muted=!0;c.playsinline=!0;c.webkitPlaysinline=!0;c.setAttribute("height","0");c.setAttribute("width","0");H(c,{position:"fixed",top:"0",width:"0",height:"0",opacity:"0"});try{var d=c.play();d&&d.catch&&d.catch(function(){})}catch(f){}return Y=Promise.resolve(!c.paused)}
function T(a,b){var c,d=a.video,f=c?Promise.resolve(c):a.getAnalyticsDetails();f.then(function(a){d.element.dispatchCustomEvent(b,a)})};function vb(a){a=AMP.BaseElement.call(this,a)||this;a.U=-1;a.L=null;a.da=null;a.O=!1;a.m=null;a.R=null;a.xa=null;a.ta=null;a.ua=null;a.wa=null;return a}aa(vb,AMP.BaseElement);h=vb.prototype;h.preconnectCallback=function(a){this.preconnect.url(wb(this));this.preconnect.url("https://s.ytimg.com",a);this.preconnect.url("https://i.ytimg.com",a)};h.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};
h.renderOutsideViewport=function(){return.75};h.viewportCallback=function(a){this.element.dispatchCustomEvent("amp:video:visibility",{visible:a})};h.buildCallback=function(){var a=this;this.L=this.element.getAttribute("data-videoid");this.da=this.element.getAttribute("data-live-channelid");xb(this);this.ta=new Promise(function(b){a.ua=b});!this.getPlaceholder()&&this.L&&yb(this);na(this.element,"video-manager",Za);B(this.element,"video-manager").register(this)};
function wb(a){if(a.xa)return a.xa;var b;xb(a);var c="";"omit"===(a.element.getAttribute("credentials")||"include")&&(c="-nocookie");c="https://www.youtube"+c+".com/embed/";b=a.L?encodeURIComponent(a.L||"")+"?":"live_stream?channel="+(encodeURIComponent(a.da||"")+"&");b=""+c+b+"enablejsapi=1";c=qa(a.element);"autoplay"in c&&(delete c.autoplay,a.user().error("AMP-YOUTUBE","Use autoplay attribute instead of data-param-autoplay"));"playsinline"in c||(c.playsinline="1");var d=a.element.hasAttribute("autoplay");
d&&("iv_load_policy"in c||(c.iv_load_policy="3"),c.playsinline="1");var f=[],g;for(g in c){var e=c[g];if(null!=e)if(Array.isArray(e))for(var k=0;k<e.length;k++){var l=e[k];f.push(encodeURIComponent(g)+"="+encodeURIComponent(l))}else f.push(encodeURIComponent(g)+"="+encodeURIComponent(e))}if(g=f.join("&"))c=b.split("#",2),b=c[0].split("?",2),g=b[0]+(b[1]?"?"+b[1]+"&"+g:"?"+g),b=g+=c[1]?"#"+c[1]:"";return a.xa=b}
h.layoutCallback=function(){var a=this,b=this.element.ownerDocument.createElement("iframe"),c=wb(this);b.setAttribute("frameborder","0");b.setAttribute("allowfullscreen","true");b.src=c;this.applyFillContent(b);this.m=b;this.wa=K(this.win,"message",this.Qa.bind(this));this.element.appendChild(this.m);var d=this.loadPromise(this.m).then(function(){a.m&&a.m.contentWindow.postMessage(JSON.stringify(v({event:"listening"})),"*");a.element.dispatchCustomEvent("load")});this.ua(d);return d};
h.unlayoutCallback=function(){var a=this;this.m&&(E(this.m),this.m=null);this.wa&&this.wa();this.U=2;this.ta=new Promise(function(b){a.ua=b});return!0};h.pauseCallback=function(){this.m&&this.m.contentWindow&&1==this.U&&this.pause()};h.mutatedAttributesCallback=function(a){void 0!==a["data-videoid"]&&(this.L=this.element.getAttribute("data-videoid"),this.m&&Z(this,"loadVideoById",[this.L]))};
function xb(a){var b=!(a.L&&a.da)&&(a.L||a.da);ga().assert(b,"Exactly one of data-videoid or data-live-channelid should be present for <amp-youtube> %s",a.element)}function Z(a,b,c){a.ta.then(function(){if(a.m&&a.m.contentWindow){var d=JSON.stringify(v({event:"command",func:b,args:c||""}));a.m.contentWindow.postMessage(d,"*")}})}
h.Qa=function(a){"https://www.youtube.com"==a.origin&&a.source==this.m.contentWindow&&a.data&&(n(a.data)||x(a.data,"{"))&&(a=n(a.data)?a.data:ka(a.data),void 0!==a&&("infoDelivery"==a.event&&a.info&&void 0!==a.info.playerState?(this.U=a.info.playerState,2==this.U?this.element.dispatchCustomEvent("pause"):0==this.U?(this.element.dispatchCustomEvent("pause"),this.element.dispatchCustomEvent("ended")):1==this.U&&this.element.dispatchCustomEvent("playing")):"infoDelivery"==a.event&&a.info&&void 0!==a.info.muted?
this.O!=a.info.muted&&(this.O=a.info.muted,this.element.dispatchCustomEvent(this.O?"muted":"unmuted")):"initialDelivery"==a.event&&a.info?this.R=a.info:"infoDelivery"==a.event&&a.info&&void 0!==a.info.currentTime&&(this.R.currentTime=a.info.currentTime)))};
function yb(a){var b=a.element.ownerDocument.createElement("img"),c=a.L;H(b,{"object-fit":"cover",visibility:"hidden"});b.src="https://i.ytimg.com/vi/"+encodeURIComponent(c)+"/sddefault.jpg#404_is_fine";b.setAttribute("placeholder","");b.setAttribute("referrerpolicy","origin");a.applyFillContent(b);a.element.appendChild(b);a.loadPromise(b).then(function(){if(120==b.naturalWidth&&90==b.naturalHeight)throw Error("sddefault.jpg is not found");}).catch(function(){b.src="https://i.ytimg.com/vi/"+encodeURIComponent(c)+
"/hqdefault.jpg";return a.loadPromise(b)}).then(function(){a.getVsync().mutate(function(){H(b,{visibility:""})})})}h.supportsPlatform=function(){return!0};h.isInteractive=function(){return!0};h.play=function(){Z(this,"playVideo")};h.pause=function(){Z(this,"pauseVideo")};h.mute=function(){Z(this,"mute")};h.unmute=function(){Z(this,"unMute")};h.showControls=function(){};h.hideControls=function(){};
h.fullscreenEnter=function(){if(this.m){var a=this.m,b=a.requestFullscreen||a.requestFullScreen||a.webkitRequestFullscreen||a.webkitRequestFullScreen||a.webkitEnterFullscreen||a.webkitEnterFullScreen||a.msRequestFullscreen||a.msRequestFullScreen||a.mozRequestFullscreen||a.mozRequestFullScreen;b&&b.call(a)}};
h.fullscreenExit=function(){if(this.m){var a=this.m,b=a.cancelFullScreen||a.exitFullscreen||a.exitFullScreen||a.webkitExitFullscreen||a.webkitExitFullScreen||a.webkitCancelFullScreen||a.mozCancelFullScreen||a.msExitFullscreen;b?b.call(a):(a.ownerDocument&&(b=a.ownerDocument.cancelFullScreen||a.ownerDocument.exitFullscreen||a.ownerDocument.exitFullScreen||a.ownerDocument.webkitExitFullscreen||a.ownerDocument.webkitExitFullScreen||a.ownerDocument.webkitCancelFullScreen||a.ownerDocument.mozCancelFullScreen||
a.ownerDocument.msExitFullscreen),b&&b.call(a.ownerDocument))}};h.isFullscreen=function(){var a;this.m?(a=this.m,a=a.webkitDisplayingFullscreen?!0:a.ownerDocument&&(a.ownerDocument.fullscreenElement||a.ownerDocument.webkitFullscreenElement||a.ownerDocument.mozFullScreenElement||a.webkitCurrentFullScreenElement)==a?!0:!1):a=!1;return a};h.getMetadata=function(){};h.preimplementsMediaSessionAPI=function(){return!0};h.getCurrentTime=function(){return this.R?this.R.currentTime:0};
h.getDuration=function(){return this.R?this.R.duration:1};h.getPlayedRanges=function(){return[]};(function(a){a.registerElement("amp-youtube",vb)})(self.AMP);
})});
//# sourceMappingURL=amp-youtube-0.1.js.map

