(self.AMP=self.AMP||[]).push({n:"amp-image-lightbox",v:"1522422854768",f:(function(AMP){var g;function l(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};self.log=self.log||{user:null,dev:null,userForEmbed:null};var n=self.log;function p(){if(!n.user)throw Error("failed to call initLogConstructor");return n.user}function q(){if(n.dev)return n.dev;throw Error("failed to call initLogConstructor");};function t(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};function u(a,b){a=a.__AMP_TOP||a;return aa(a,b)}function ba(a){a=ca(a);a=ca(a);a=a.isSingleDoc()?a.win:a;return aa(a,"history")}function ca(a){return a.nodeType?u((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function aa(a,b){var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function da(a,b){for(var c,d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null}function ea(a){var b="figure";if(a.closest)return a.closest(b);b=b.toUpperCase();return da(a,function(a){return a.tagName==b})}function fa(a,b){var c=a.getElementsByTagName(b);return c[0]||null};var v,ga="Webkit webkit Moz moz ms O o".split(" ");function ha(a,b,c){var d;var e=a.style;if(!t(b,"--")){v||(v=Object.create(null));var f=v[b];if(!f){f=b;if(void 0===e[b]){var h=b.charAt(0).toUpperCase()+b.slice(1);b:{for(var k=0;k<ga.length;k++){var m=ga[k]+h;if(void 0!==e[m]){h=m;break b}}h=""}void 0!==e[h]&&(f=h)}v[b]=f}b=f}b&&(a.style[b]=d?c+d:c)}function w(a,b){for(var c in b)ha(a,c,b[c])};function x(a){return!!(a.complete||"complete"==a.readyState||a.document&&"complete"==a.document.readyState)};function y(){this.M=null}g=y.prototype;g.add=function(a){var b=this;this.M||(this.M=[]);this.M.push(a);return function(){b.remove(a)}};g.remove=function(a){this.M&&(a=this.M.indexOf(a),-1<a&&this.M.splice(a,1))};g.removeAll=function(){this.M&&(this.M.length=0)};g.fire=function(a){if(this.M)for(var b=this.M,c=0;c<b.length;c++)(0,b[c])(a)};g.getHandlerCount=function(){return this.M?this.M.length:0};function z(a,b,c,d){return{left:a,top:b,width:c,height:d,bottom:b+d,right:a+c,x:a,y:b}}function A(a){return z(Number(a.left),Number(a.top),Number(a.width),Number(a.height))};function ia(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};function B(a,b,c){var d=this;this.ab=u(a,"timer");this.hb=b;this.fb=c||0;this.ka=-1;this.La=0;this.X=!1;this.cb=function(){return d.ua()}}B.prototype.isPending=function(){return-1!=this.ka};B.prototype.schedule=function(a){var b=a||this.fb;this.X&&10>b&&(b=10);var c=Date.now()+b;return!this.isPending()||-10>c-this.La?(this.cancel(),this.La=c,this.ka=this.ab.delay(this.cb,b),!0):!1};B.prototype.ua=function(){this.ka=-1;this.La=0;this.X=!0;this.hb();this.X=!1};
B.prototype.cancel=function(){this.isPending()&&(this.ab.cancel(this.ka),this.ka=-1)};var ja=/(\S+)(?:\s+(?:(-?\d+(?:\.\d+)?)([a-zA-Z]*)))?\s*(?:,|$)/g;function ka(a){var b=a.getAttribute("srcset");if(b){a=[];for(var c;c=ja.exec(b);){var d=c[1],e=void 0,f;if(c[2]){var h=c[3].toLowerCase();if("w"==h)e=parseInt(c[2],10);else if("x"==h)f=parseFloat(c[2]);else continue}else f=1;a.push({url:d,width:e,dpr:f})}return new C(a)}var k=p().assert(a.getAttribute("src"),'Either non-empty "srcset" or "src" attribute must be specified: %s',a);return new C([{url:k,width:void 0,dpr:1}])}
function C(a){p().assert(0<a.length,"Srcset must have at least one source");this.oa=a;for(var b=!1,c=!1,d=0;d<a.length;d++)var e=a[d],b=b||!!e.width,c=c||!!e.dpr;p().assert(!!(b^c),"Srcset must have width or dpr sources, but not both");a.sort(b?la:ma);this.bb=b;this.tb=c}
C.prototype.select=function(a,b){if(this.bb){b*=a;a=this.oa;for(var c=0,d=Infinity,e=Infinity,f=0;f<a.length;f++){var h=a[f].width,k=Math.abs(h-b);if(k<=1.1*d||1.2<b/e)c=f,d=k,e=h;else break}}else for(a=this.oa,c=0,d=Infinity,e=0;e<a.length;e++)if(f=Math.abs(a[e].dpr-b),f<=d)c=e,d=f;else break;b=c;return this.oa[b].url};C.prototype.getUrls=function(){return this.oa.map(function(a){return a.url})};
C.prototype.stringify=function(a){for(var b=[],c=this.oa,d=0;d<c.length;d++){var e=c[d],f=e.url;a&&(f=a(f));f=this.bb?f+(" "+e.width+"w"):f+(" "+e.dpr+"x");b.push(f)}return b.join(", ")};function la(a,b){p().assert(a.width!=b.width,"Duplicate width: %s",a.width);return a.width-b.width}function ma(a,b){p().assert(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return a.dpr-b.dpr};function na(a,b,c,d){this.type=a;this.data=b;this.time=c;this.event=d}
function oa(a,b){this.T=a;this.w=[];this.da=[];this.P=[];this.A=[];this.o=null;this.nb=b;this.za=!1;this.ua=new B(a.ownerDocument.defaultView,this.Wa.bind(this));this.Ya=new y;this.ia=Object.create(null);this.Ua=this.mb.bind(this);this.Sa=this.kb.bind(this);this.Ta=this.lb.bind(this);this.Ra=this.jb.bind(this);this.T.addEventListener("touchstart",this.Ua);this.T.addEventListener("touchend",this.Sa);this.T.addEventListener("touchmove",this.Ta);this.T.addEventListener("touchcancel",this.Ra);this.Ma=
!1}function pa(a){var b;b=void 0===b?!1:b;var c=a.__AMP_Gestures;c||(c=new oa(a,b),a.__AMP_Gestures=c);return c}g=oa.prototype;g.cleanup=function(){this.T.removeEventListener("touchstart",this.Ua);this.T.removeEventListener("touchend",this.Sa);this.T.removeEventListener("touchmove",this.Ta);this.T.removeEventListener("touchcancel",this.Ra);delete this.T.__AMP_Gestures;this.ua.cancel()};
g.onGesture=function(a,b){var c=new a(this),d=c.getType(),e=this.ia[d];e||(this.w.push(c),e=new y,this.ia[d]=e);return e.add(b)};g.removeGesture=function(a){var b=(new a(this)).getType();if(a=this.ia[b]){a.removeAll();a=ia(this.w,function(a){return a.getType()==b});if(0>a)return!1;this.w.splice(a,1);this.P.splice(a,1);this.A.splice(a,1);this.da.splice(a,1);delete this.ia[b];return!0}return!1};g.onPointerDown=function(a){return this.Ya.add(a)};
g.mb=function(a){var b=Date.now();this.za=!1;this.Ya.fire(a);for(var c=0;c<this.w.length;c++)if(!this.P[c]&&(this.A[c]&&this.A[c]<b&&D(this,c),this.w[c].onTouchStart(a))){var d=c;this.da[d]=!0;this.A[d]=0}E(this,a)};g.lb=function(a){for(var b=Date.now(),c=0;c<this.w.length;c++)this.da[c]&&(this.A[c]&&this.A[c]<b?D(this,c):this.w[c].onTouchMove(a)||D(this,c));E(this,a)};
g.kb=function(a){for(var b=Date.now(),c=0;c<this.w.length;c++)this.da[c]&&(this.A[c]&&this.A[c]<b?D(this,c):(this.w[c].onTouchEnd(a),(!this.A[c]||this.A[c]<b)&&D(this,c)));E(this,a)};g.jb=function(a){for(var b=0;b<this.w.length;b++){var c=b;this.P[c]=0;D(this,c)}E(this,a)};function E(a,b){var c=!!a.o||a.za;a.za=!1;if(!c)for(var d=Date.now(),e=0;e<a.w.length;e++)if(a.P[e]||a.A[e]&&a.A[e]>=d){c=!0;break}c&&(b.stopPropagation(),a.nb||b.preventDefault());a.Ma&&(a.Ma=!1,a.Wa())}
g.Wa=function(){for(var a=Date.now(),b=-1,c=0;c<this.w.length;c++)if(!this.P[c])this.A[c]&&this.A[c]<a&&D(this,c);else if(-1==b||this.P[c]>this.P[b])b=c;if(-1!=b){for(var d=0,c=0;c<this.w.length;c++)!this.P[c]&&this.da[c]&&(d=Math.max(d,this.A[c]-a));if(2>d){for(var a=b,c=this.w[a],e=0;e<this.w.length;e++)if(e!=a){var f=e;this.P[f]=0;D(this,f)}this.P[a]=0;this.A[a]=0;this.o=c;c.acceptStart()}else this.ua.schedule(d)}};function D(a,b){a.da[b]=!1;a.A[b]=0;a.P[b]||a.w[b].acceptCancel()}
function F(a,b){this.sb=a;this.sa=b}g=F.prototype;g.getType=function(){return this.sb};g.signalReady=function(a){var b=this.sa;if(b.o)this.acceptCancel();else{for(var c=Date.now(),d=0;d<b.w.length;d++)b.w[d]==this&&(b.P[d]=c+a,b.A[d]=0);b.Ma=!0}};g.signalPending=function(a){var b=this.sa;if(b.o)this.acceptCancel();else for(var c=Date.now(),d=0;d<b.w.length;d++)b.w[d]==this&&(b.A[d]=c+a)};g.signalEnd=function(){var a=this.sa;a.o==this&&(a.o=null,a.za=!0)};
g.signalEmit=function(a,b){var c=this.sa.ia[this.getType()];c&&c.fire(new na(this.getType(),a,Date.now(),b))};g.acceptStart=function(){};g.acceptCancel=function(){};g.onTouchStart=function(){return!1};g.onTouchMove=function(){return!1};g.onTouchEnd=function(){};function qa(){}var ra=Math.round(-16.67/Math.log(.95));function G(a,b,c){1>b&&(b=1);var d=a/b,e=.5+Math.min(b/33.34,.5);return d*e+c*(1-e)}function sa(a,b,c,d,e,f){var h;return(new ta(a,b,c,d,e,f,h)).Pa()}function ta(a,b,c,d,e,f,h){var k=this;this.$=h||u(self,"vsync");this.Y=a;this.Aa=f;this.c=b;this.h=c;this.Ea=d;this.Fa=e;this.F=this.D=0;this.H=this.U=Date.now();this.ja=new Promise(function(a,b){k.Oa=a;k.Na=b});this.fa=!1}g=ta.prototype;
g.Pa=function(){this.fa=!0;if(.02>=Math.abs(this.Ea)&&.02>=Math.abs(this.Fa))this.Aa(this.c,this.h),this.Ba(!0);else{this.D=this.Ea;this.F=this.Fa;var a=this.ob.bind(this),b=this.Ba.bind(this,!0);this.$.runAnimMutateSeries(this.Y,a,5E3).then(b,b)}return this};g.halt=function(){this.fa&&this.Ba(!1)};g.then=function(a,b){return a||b?this.ja.then(a,b):this.ja};g.thenAlways=function(a){a=a||qa;return this.then(a,a)};
g.ob=function(a,b){if(!this.fa)return!1;this.H=Date.now();this.c+=b*this.D;this.h+=b*this.F;if(!this.Aa(this.c,this.h))return!1;var c=Math.exp(-a/ra);this.D=this.Ea*c;this.F=this.Fa*c;return.02<Math.abs(this.D)||.02<Math.abs(this.F)};g.Ba=function(a){this.fa&&(this.fa=!1,this.H=Date.now(),this.Aa(this.c,this.h),a?this.Oa():this.Na())};function H(a){F.call(this,"tap",a);this.h=this.c=this.l=this.m=0}l(H,F);H.prototype.onTouchStart=function(a){return(a=a.touches)&&1==a.length?(this.m=a[0].clientX,this.l=a[0].clientY,!0):!1};H.prototype.onTouchMove=function(a){return(a=a.changedTouches||a.touches)&&1==a.length&&(this.c=a[0].clientX,this.h=a[0].clientY,a=8<=Math.abs(this.h-this.l),8<=Math.abs(this.c-this.m)||a)?!1:!0};H.prototype.onTouchEnd=function(){this.signalReady(0)};
H.prototype.acceptStart=function(){this.signalEmit({clientX:this.c,clientY:this.h},null);this.signalEnd()};function I(a){F.call(this,"doubletap",a);this.R=this.h=this.c=this.l=this.m=0;this.Xa=null}l(I,F);g=I.prototype;g.onTouchStart=function(a){return 1<this.R?!1:(a=a.touches)&&1==a.length?(this.m=a[0].clientX,this.l=a[0].clientY,this.c=a[0].clientX,this.h=a[0].clientY,!0):!1};
g.onTouchMove=function(a){return(a=a.touches)&&1==a.length?(this.c=a[0].clientX,this.h=a[0].clientY,a=8<=Math.abs(this.h-this.l),8<=Math.abs(this.c-this.m)||a?(this.acceptCancel(),!1):!0):!1};g.onTouchEnd=function(a){this.R++;2>this.R?this.signalPending(300):(this.Xa=a,this.signalReady(0))};g.acceptStart=function(){this.R=0;this.signalEmit({clientX:this.c,clientY:this.h},this.Xa);this.signalEnd()};g.acceptCancel=function(){this.R=0};
function J(a,b,c,d){F.call(this,a,b);this.qa=c;this.xa=d;this.o=!1;this.F=this.D=this.W=this.H=this.U=this.ca=this.ba=this.h=this.c=this.l=this.m=0}l(J,F);g=J.prototype;g.onTouchStart=function(a){return(a=a.touches)&&1==a.length?(this.U=Date.now(),this.m=a[0].clientX,this.l=a[0].clientY,!0):!1};
g.onTouchMove=function(a){var b=a.touches;if(b&&1==b.length){var c=b[0].clientX,b=b[0].clientY;this.c=c;this.h=b;if(this.o)this.Z(!1,!1,a);else if(a=Math.abs(c-this.m),c=Math.abs(b-this.l),this.qa&&this.xa)(8<=a||8<=c)&&this.signalReady(-10);else if(this.qa)if(8<=a&&a>c)this.signalReady(-10);else{if(8<=c)return!1}else if(this.xa)if(8<=c&&c>a)this.signalReady(-10);else{if(8<=a)return!1}else return!1;return!0}return!1};g.onTouchEnd=function(a){this.Ca(a)};
g.acceptStart=function(){this.o=!0;this.ba=this.m;this.ca=this.l;this.W=this.U;this.m=this.c;this.l=this.h;this.Z(!0,!1,null)};g.acceptCancel=function(){this.o=!1};
g.Z=function(a,b,c){this.H=Date.now();var d=this.H-this.W;if(!b&&4<d||b&&16<d)this.D=G(this.c-this.ba,d,this.D),this.F=G(this.h-this.ca,d,this.F),this.D=1E-4<Math.abs(this.D)?this.D:0,this.F=1E-4<Math.abs(this.F)?this.F:0,this.ba=this.c,this.ca=this.h,this.W=this.H;this.signalEmit({first:a,last:b,time:this.H,deltaX:this.qa?this.c-this.m:0,deltaY:this.xa?this.h-this.l:0,velocityX:this.qa?this.D:0,velocityY:this.xa?this.F:0},c)};g.Ca=function(a){this.o&&(this.o=!1,this.Z(!1,!0,a),this.signalEnd())};
function K(a){J.call(this,"swipe-xy",a,!0,!0)}l(K,J);function L(a){F.call(this,"tapzoom",a);this.o=!1;this.F=this.D=this.W=this.H=this.U=this.ca=this.ba=this.R=this.rb=this.qb=this.h=this.c=this.l=this.m=0}l(L,F);g=L.prototype;g.onTouchStart=function(a){return this.o?!1:(a=a.touches)&&1==a.length?(this.m=a[0].clientX,this.l=a[0].clientY,!0):!1};
g.onTouchMove=function(a){var b=a.touches;if(b&&1==b.length){this.c=b[0].clientX;this.h=b[0].clientY;if(this.o)this.Z(!1,!1,a);else if(a=8<=Math.abs(this.h-this.l),8<=Math.abs(this.c-this.m)||a){if(0==this.R)return this.acceptCancel(),!1;this.signalReady(0)}return!0}return!1};g.onTouchEnd=function(a){this.o?this.Ca(a):(this.R++,1==this.R?(this.signalPending(400),this.qb=this.c,this.rb=this.h):this.acceptCancel())};g.acceptStart=function(){this.R=0;this.o=!0;this.Z(!0,!1,null)};
g.acceptCancel=function(){this.R=0;this.o=!1};g.Z=function(a,b,c){this.H=Date.now();a?(this.U=this.H,this.D=this.F=0):2<this.H-this.W&&(this.D=G(this.c-this.ba,this.H-this.W,this.D),this.F=G(this.h-this.ca,this.H-this.W,this.F));this.ba=this.c;this.ca=this.h;this.W=this.H;this.signalEmit({first:a,last:b,centerClientX:this.m,centerClientY:this.l,deltaX:this.c-this.m,deltaY:this.h-this.l,velocityX:this.D,velocityY:this.F},c)};g.Ca=function(a){this.o&&(this.o=!1,this.Z(!1,!0,a),this.signalEnd())};function M(a,b,c,d){var e=new ua(0,0,a,b,c,d,1,1);return e.solveYValueFromXValue.bind(e)}function ua(a,b,c,d,e,f,h,k){this.x0=a;this.y0=b;this.x1=c;this.y1=d;this.x2=e;this.y2=f;this.x3=h;this.y3=k}g=ua.prototype;g.solveYValueFromXValue=function(a){return this.getPointY(this.solvePositionFromXValue(a))};
g.solvePositionFromXValue=function(a){var b=1E-6,c=(a-this.x0)/(this.x3-this.x0);if(0>=c)return 0;if(1<=c)return 1;for(var d=0,e=1,f=0,h=0;8>h;h++){var f=this.getPointX(c),k=(this.getPointX(c+b)-f)/b;if(Math.abs(f-a)<b)return c;if(Math.abs(k)<b)break;else f<a?d=c:e=c,c-=(f-a)/k}for(h=0;Math.abs(f-a)>b&&8>h;h++)f<a?(d=c,c=(c+e)/2):(e=c,c=(c+d)/2),f=this.getPointX(c);return c};
g.getPointX=function(a){if(0==a)return this.x0;if(1==a)return this.x3;var b=this.lerp(this.x0,this.x1,a),c=this.lerp(this.x1,this.x2,a),d=this.lerp(this.x2,this.x3,a),b=this.lerp(b,c,a),c=this.lerp(c,d,a);return this.lerp(b,c,a)};g.getPointY=function(a){if(0==a)return this.y0;if(1==a)return this.y3;var b=this.lerp(this.y0,this.y1,a),c=this.lerp(this.y1,this.y2,a),d=this.lerp(this.y2,this.y3,a),b=this.lerp(b,c,a),c=this.lerp(c,d,a);return this.lerp(b,c,a)};g.lerp=function(a,b,c){return a+c*(b-a)};
var va=M(.25,.1,.25,1),wa=M(.42,0,1,1),xa=M(0,0,.58,1),ya=M(.42,0,.58,1),za={linear:function(a){return a},ease:va,"ease-in":wa,"ease-out":xa,"ease-in-out":ya};function Aa(a){if(!a)return null;if("string"==typeof a){if(-1!=a.indexOf("cubic-bezier")){var b=a.match(/cubic-bezier\((.+)\)/);if(b&&(b=b[1].split(",").map(parseFloat),4==b.length)){for(var c=0;4>c;c++)if(isNaN(b[c]))return null;return M(b[0],b[1],b[2],b[3])}return null}return za[a]}return a};function Ba(){}function N(a,b){this.Y=a;this.$=b||u(self,"vsync");this.Va=null;this.J=[]}function Ca(a,b,c){var d=Da;return(new N(a)).setCurve(d).add(0,b,1).start(c)}N.prototype.setCurve=function(a){a&&(this.Va=Aa(a));return this};N.prototype.add=function(a,b,c,d){this.J.push({delay:a,func:b,duration:c,curve:Aa(d)});return this};N.prototype.start=function(a){var b=new Ea(this.$,this.Y,this.J,this.Va,a);b.Pa();return b};
function Ea(a,b,c,d,e){var f=this;this.$=a;this.Y=b;this.J=[];for(b=0;b<c.length;b++){var h=c[b];this.J.push({delay:h.delay,func:h.func,duration:h.duration,curve:h.curve||d,started:!1,completed:!1})}this.gb=e;this.vb=this.ub=this.U=0;this.X=!1;this.Za={};this.ja=new Promise(function(a,b){f.Oa=a;f.Na=b});this.$a=this.$.createAnimTask(this.Y,{mutate:this.pb.bind(this)})}g=Ea.prototype;g.then=function(a,b){return a||b?this.ja.then(a,b):this.ja};g.thenAlways=function(a){a=a||Ba;return this.then(a,a)};
g.halt=function(a){O(this,!1,a||0)};g.Pa=function(){this.U=Date.now();this.X=!0;this.$.canAnimate(this.Y)?this.$a(this.Za):(q().warn("Animation","cannot animate"),O(this,!1,0))};function O(a,b,c){if(a.X){a.X=!1;if(0!=c){1<a.J.length&&a.J.sort(function(a,b){return a.delay+a.duration-(b.delay+b.duration)});try{if(0<c)for(c=0;c<a.J.length;c++)a.J[c].func(1,!0);else for(var d=a.J.length-1;0<=d;d--)a.J[d].func(0,!1)}catch(e){q().error("Animation","completion failed: "+e,e),b=!1}}b?a.Oa():a.Na()}}
g.pb=function(){if(this.X){for(var a=Date.now(),b=Math.min((a-this.U)/this.gb,1),c=0;c<this.J.length;c++){var d=this.J[c];!d.started&&b>=d.delay&&(d.started=!0)}for(c=0;c<this.J.length;c++)if(d=this.J[c],d.started&&!d.completed)a:{var e,f;if(0<d.duration){if(e=f=Math.min((b-d.delay)/d.duration,1),d.curve&&1!=e)try{e=d.curve(f)}catch(h){q().error("Animation","step curve failed: "+h,h);O(this,!1,0);break a}}else e=f=1;1==f&&(d.completed=!0);try{d.func(e,d.completed)}catch(h){q().error("Animation","step mutate failed: "+
h,h),O(this,!1,0)}}1==b?O(this,!0,0):this.$.canAnimate(this.Y)?this.$a(this.Za):(q().warn("Animation","cancel animation"),O(this,!1,0))}};function Fa(a){var b;b=void 0===b?" ":b;return function(c,d){for(var e=[],f=0;f<a.length;f++){var h=(0,a[f])(c,d);"string"==typeof h&&e.push(h)}return e.join(b)}}function P(a,b){return function(c,d){for(var e in b)ha(a,e,b[e](c,d))}}function Q(a,b){return function(c){return a+(b-a)*c}}function Ga(a,b){return function(c){var d=a(c);"number"==typeof d&&(d+="px");if(!b)return"translate("+d+")";c=b(c);"number"==typeof c&&(c+="px");return"translate("+d+","+c+")"}}
function Ha(a){return function(b){return"scale("+a(b)+")"}};var Ia={"amp-img":!0,"amp-anim":!0},R=M(.4,0,.2,1),S=M(.4,0,.2,1),Da=M(.4,0,.2,1.4);
function Ja(a,b,c){this.ra=a;this.win=b;this.ib=c;this.ya=a.element.ownerDocument.createElement("div");this.ya.classList.add("i-amphtml-image-lightbox-viewer");this.C=a.element.ownerDocument.createElement("img");this.C.classList.add("i-amphtml-image-lightbox-viewer-image");this.ya.appendChild(this.C);this.va=null;this.aa={alt:null,"aria-label":null,"aria-labelledby":null};this.ma=this.na=0;this.B=z(0,0,0,0);this.N=z(0,0,0,0);this.Ia=this.ta=this.pa=this.j=1;this.ha=2;this.Ha=this.Ga=this.Ka=this.Ja=
this.G=this.I=this.l=this.m=0;this.V=null;Ka(this)}g=Ja.prototype;g.getElement=function(){return this.ya};g.getImage=function(){return this.C};g.getViewerBox=function(){return this.B};g.getImageBox=function(){return this.N};g.getImageBoxWithOffset=function(){var a;if(0==this.I&&0==this.G)a=this.N;else{a=this.N;var b=this.I,c=this.G;a=0==b&&0==c||0==a.width&&0==a.height?a:z(a.left+b,a.top+c,a.width,a.height)}return a};
g.reset=function(){var a=this;this.C.setAttribute("src","");Object.keys(this.aa).forEach(function(b){a.C.removeAttribute(b);a.aa[b]=null});this.C.removeAttribute("aria-describedby");this.va=null;this.N=z(0,0,0,0);this.ma=this.na=0;this.pa=this.j=this.ta=1;this.ha=2;this.Ha=this.Ga=this.Ka=this.Ja=this.G=this.I=this.l=this.m=0;this.V&&this.V.halt();this.V=null};
g.init=function(a,b){var c=this;this.na=a.offsetWidth;this.ma=a.offsetHeight;this.va=ka(a);Object.keys(this.aa).forEach(function(b){c.aa[b]=a.getAttribute(b);c.aa[b]&&c.C.setAttribute(b,c.aa[b])});b&&x(b)&&b.src&&this.C.setAttribute("src",b.src)};
g.measure=function(){this.B=A(this.ya.getBoundingClientRect());var a=this.na/this.ma,b=Math.min(this.B.width/a,this.B.height),c=Math.min(this.B.height*a,this.B.width);16>=Math.abs(c-this.na)&&16>=Math.abs(b-this.ma)&&(c=this.na,b=this.ma);this.N=z(Math.round((this.B.width-c)/2),Math.round((this.B.height-b)/2),Math.round(c),Math.round(b));w(this.C,{top:this.N.top+"px",left:this.N.left+"px",width:this.N.width+"px",height:this.N.height+"px"});var d=this.B.width/this.B.height,e=Math.max(d/a,a/d);this.ha=
Math.max(2,e);this.pa=this.j=1;this.l=this.G=this.m=this.I=0;T(this,this.j);U(this);return La(this)};function La(a){if(!a.va)return Promise.resolve();a.ta=Math.max(a.ta,a.j);var b=a.va.select(a.N.width*a.ta,a.ra.getDpr());return b==a.C.getAttribute("src")?Promise.resolve():u(a.win,"timer").promise(1).then(function(){a.C.setAttribute("src",b);return a.ib(a.C)})}
function Ka(a){var b=pa(a.C);b.onGesture(H,function(){a.ra.toggleViewMode()});b.onGesture(K,function(b){var c=b.data.deltaY,e=V(a,a.m+b.data.deltaX,!0),c=W(a,a.l+c,!0);X(a,a.j,e,c,!1);b.data.last&&Ma(a,b.data.velocityX,b.data.velocityY)});b.onPointerDown(function(){a.V&&a.V.halt()});b.onGesture(I,function(b){var c;c=1==a.j?a.ha:a.Ia;Na(a,c,a.B.width/2-b.data.clientX,a.B.height/2-b.data.clientY,!0).then(function(){return Oa(a,0,0,0,0,0,0)})});b.onGesture(L,function(b){Pa(a,b.data.centerClientX,b.data.centerClientY,
b.data.deltaX,b.data.deltaY);b.data.last&&Oa(a,b.data.centerClientX,b.data.centerClientY,b.data.deltaX,b.data.deltaY,b.data.velocityY,b.data.velocityY)})}function Y(a,b,c,d){return Math.max(b-d,Math.min(c+d,a))}function V(a,b,c){return Y(b,a.Ja,a.Ga,c&&1<a.j?.25*a.B.width:0)}function W(a,b,c){return Y(b,a.Ka,a.Ha,c?.25*a.B.height:0)}
function T(a,b){var c=0,d=0,e=a.B.height-a.N.height*b;0<=e?d=c=0:(d=e/2,c=-d);var f=0,h=0;b=a.B.width-a.N.width*b;0<=b?h=f=0:(h=b/2,f=-h);a.Ja=h;a.Ka=d;a.Ga=f;a.Ha=c}function U(a){var b=a.C,c;c=a.I;var d=a.G;"number"==typeof c&&(c+="px");void 0===d?c="translate("+c+")":("number"==typeof d&&(d+="px"),c="translate("+c+", "+d+")");w(b,{transform:c+" "+("scale("+a.j+")")});1!=a.j&&a.ra.toggleViewMode(!0)}
function Ma(a,b,c){var d=a.G-a.l;1==a.j&&10<Math.abs(d)?a.ra.close():(a.V=sa(a.C,a.I,a.G,b,c,function(b,c){b=V(a,b,!0);c=W(a,c,!0);if(1>Math.abs(b-a.I)&&1>Math.abs(c-a.G))return!1;X(a,a.j,b,c,!1);return!0}),a.V.thenAlways(function(){a.V=null;return Qa(a)}))}function Pa(a,b,c,d,e){var f=Math.sqrt(d*d+e*e),h=Math.abs(e)>Math.abs(d)?Math.sign(e):Math.sign(-d);if(0!=h){var k=a.pa*(1+h*f/100),m=a.B.width/2-b,r=a.B.height/2-c;d=Math.min(m,f/100*m);e=Math.min(r,f/100*r);Na(a,k,d,e,!1)}}
function Na(a,b,c,d,e){b=Y(b,a.Ia,a.ha,.25);if(b!=a.j)return T(a,b),c=V(a,a.m+c*b,!1),d=W(a,a.l+d*b,!1),X(a,b,c,d,e)}function Oa(a,b,c,d,e,f,h){d=0==f&&0==h?Promise.resolve():sa(a.C,d,e,f,h,function(d,e){Pa(a,b,c,d,e);return!0}).thenAlways();var k=a.j>a.pa;return d.then(function(){return Qa(a)}).then(function(){k&&La(a)})}
function X(a,b,c,d,e){var f=b-a.j,h=c-a.I,k=d-a.G,h=Math.sqrt(h*h+k*k),m=0;if(e)var r=250,m=Math.min(r,Math.max(r*h*.01,r*Math.abs(f)));if(16<m&&e){var Sa=Q(a.j,b),Ta=Q(a.I,c),Ua=Q(a.G,d);e=Ca(a.C,function(b){a.j=Sa(b);a.I=Ta(b);a.G=Ua(b);U(a)},m).thenAlways(function(){a.j=b;a.I=c;a.G=d;U(a)})}else a.j=b,a.I=c,a.G=d,U(a),e=e?Promise.resolve():void 0;return e}
function Qa(a){var b=Y(a.j,a.Ia,a.ha,0);b!=a.j&&T(a,b);var c=V(a,a.I/a.j*b,!1),d=W(a,a.G/a.j*b,!1);return X(a,b,c,d,!0).then(function(){a.pa=a.j;a.m=a.I;a.l=a.G})}function Z(a){a=AMP.BaseElement.call(this,a)||this;a.Da=-1;a.ea=!1;a.ga=!1;a.la=null;a.K=null;a.wa=null;a.L=null;a.O=null;a.S=null;a.Qa=a.eb.bind(a);return a}l(Z,AMP.BaseElement);g=Z.prototype;g.isLayoutSupported=function(a){return"nodisplay"==a};
function Ra(a){if(!a.L){a.L=a.element.ownerDocument.createElement("div");a.L.classList.add("i-amphtml-image-lightbox-container");a.element.appendChild(a.L);a.O=new Ja(a,a.win,a.loadPromise.bind(a));a.L.appendChild(a.O.getElement());a.S=a.element.ownerDocument.createElement("div");a.S.setAttribute("id",a.element.getAttribute("id")+"-caption");a.S.classList.add("amp-image-lightbox-caption");a.S.classList.add("i-amphtml-image-lightbox-caption");a.L.appendChild(a.S);var b=a.element.ownerDocument.createElement("button"),
c=a.element.getAttribute("data-close-button-aria-label")||"Close the lightbox";b.textContent=c;b.classList.add("i-amphtml-screen-reader");b.tabIndex=-1;b.addEventListener("click",function(){a.close()});a.element.appendChild(b);var d=pa(a.element);a.element.addEventListener("click",function(b){a.ga||a.O.getImage().contains(b.target)||a.close()});d.onGesture(H,function(){a.ga||a.close()});d.onGesture(K,function(){})}}
g.activate=function(a){var b=this;if(!this.ea){Ra(this);var c=a.caller;p().assert(c&&Ia[c.tagName.toLowerCase()],"Unsupported element: %s",c.tagName);this.ea=!0;Va(this);Wa(this,c);this.win.document.documentElement.addEventListener("keydown",this.Qa);this.getViewport().enterLightboxMode();Xa(this);this.wa=this.getViewport().onChanged(function(){b.ea&&(t(u(b.win,"platform").getIosVersionString(),"10.3")?u(b.win,"timer").delay(function(){b.O.measure()},500):b.O.measure())});ba(this.getAmpDoc()).push(this.close.bind(this)).then(function(a){b.Da=
a})}};g.eb=function(a){27==a.keyCode&&this.close()};g.close=function(){if(this.ea&&(this.ga=this.ea=!1,Ya(this),this.wa&&(this.wa(),this.wa=null),this.getViewport().leaveLightboxMode(),-1!=this.Da&&ba(this.getAmpDoc()).pop(this.Da),this.win.document.documentElement.removeEventListener("keydown",this.Qa),this.la))try{this.la.focus()}catch(a){}};g.toggleViewMode=function(a){void 0!==a?this.L.classList.toggle("i-amphtml-image-lightbox-view-mode",a):this.L.classList.toggle("i-amphtml-image-lightbox-view-mode")};
function Wa(a,b){a.la=b;a.K=fa(b,"img");a.O.init(a.la,a.K);var c=null,d=ea(b);d&&(c=fa(d,"figcaption"));if(!c)var e=b.getAttribute("aria-describedby"),c=a.element.ownerDocument.getElementById(e);if(c){var f=c;b=a.S;for(var h=b.ownerDocument.createDocumentFragment(),f=f.firstChild;f;f=f.nextSibling)h.appendChild(f.cloneNode(!0));b.appendChild(h);a.O.getImage().setAttribute("aria-describedby",a.S.getAttribute("id"))}a.S.classList.toggle("i-amphtml-empty",!c)}
function Va(a){a.O.reset();for(var b=a.S;b.firstChild;)b.removeChild(b.firstChild);a.la=null;a.K=null;a.toggleViewMode(!1)}
function Xa(a){a.ga=!0;w(a.element,{opacity:0,display:""});a.O.measure();var b=new N(a.element);b.add(0,P(a.element,{opacity:Q(0,1)}),.6,R);var c=null;if(a.K&&x(a.K)&&a.K.src){c=a.element.ownerDocument.createElement("div");c.classList.add("i-amphtml-image-lightbox-trans");a.element.ownerDocument.body.appendChild(c);var d=A(a.K.getBoundingClientRect()),e=a.O.getImageBox(),f=a.K.cloneNode(!0);f.className="";w(f,{position:"absolute",top:d.top+"px",left:d.left+"px",width:d.width+"px",height:d.height+
"px",transformOrigin:"top left",willChange:"transform"});c.appendChild(f);a.K.classList.add("i-amphtml-ghost");var h=e.top-d.top,k=0!=d.width?e.width/d.width:1,m=Math.max(.2,Math.min(.8,Math.abs(h)/250*.8));b.add(0,P(f,{transform:Fa([Ga(Q(0,e.left-d.left),Q(0,h)),Ha(Q(1,k))])}),m,R);w(a.L,{opacity:0});b.add(.8,P(a.L,{opacity:Q(0,1)}),.1,R);b.add(.9,P(c,{opacity:Q(1,.01)}),.1,S)}b.start(500).thenAlways(function(){a.ga=!1;w(a.element,{opacity:""});w(a.L,{opacity:""});c&&a.element.ownerDocument.body.removeChild(c)})}
function Ya(a){var b=a.O.getImage(),c=a.O.getImageBoxWithOffset(),d=new N(a.element),e=500;d.add(0,P(a.element,{opacity:Q(1,0)}),.9,S);var f=null;if(x(b)&&b.src&&a.K){f=a.element.ownerDocument.createElement("div");f.classList.add("i-amphtml-image-lightbox-trans");a.element.ownerDocument.body.appendChild(f);var h=A(a.K.getBoundingClientRect()),k=b.cloneNode(!0);w(k,{position:"absolute",top:c.top+"px",left:c.left+"px",width:c.width+"px",height:c.height+"px",transform:"",transformOrigin:"top left",willChange:"transform"});
f.appendChild(k);d.add(0,P(a.L,{opacity:Q(1,0)}),.1,S);var b=h.top-c.top,m=0!=c.width?h.width/c.width:1,r=P(k,{transform:Fa([Ga(Q(0,h.left-c.left),Q(0,b)),Ha(Q(1,m))])}),c=Math.max(.2,Math.min(.8,Math.abs(b)/250*.8));d.add(Math.min(.8-c,.2),function(b,c){r(b);c&&a.K.classList.remove("i-amphtml-ghost")},c,S);d.add(.8,P(f,{opacity:Q(1,.01)}),.2,S);e=Math.max(Math.min(Math.abs(b)/250*e,e),300)}d.start(e).thenAlways(function(){a.K&&a.K.classList.remove("i-amphtml-ghost");a.collapse();w(a.element,{opacity:""});
w(a.L,{opacity:""});f&&a.element.ownerDocument.body.removeChild(f);Va(a)})}(function(a){a.registerElement("amp-image-lightbox",Z,"amp-image-lightbox{position:fixed!important;top:0!important;left:0!important;bottom:0!important;right:0!important;margin:0!important;padding:0!important;overflow:hidden!important;-webkit-transform:translateZ(0)!important;transform:translateZ(0)!important;-ms-touch-action:none!important;touch-action:none!important;z-index:1000;background:rgba(0,0,0,0.95);color:#f2f2f2}.i-amphtml-image-lightbox-container{position:absolute;z-index:0;top:0;left:0;right:0;bottom:0;overflow:hidden;-webkit-transform:translateZ(0);transform:translateZ(0)}.i-amphtml-image-lightbox-trans{pointer-events:none!important;position:fixed;z-index:1001;top:0;left:0;bottom:0;right:0}.i-amphtml-image-lightbox-caption{position:absolute!important;z-index:2;bottom:0!important;left:0!important;right:0!important}.i-amphtml-image-lightbox-caption.i-amphtml-empty,.i-amphtml-image-lightbox-view-mode .i-amphtml-image-lightbox-caption{visibility:hidden}.amp-image-lightbox-caption{background:rgba(0,0,0,0.5);max-height:25%;padding:8px}.i-amphtml-image-lightbox-viewer{position:absolute;z-index:1;top:0;left:0;right:0;bottom:0;overflow:hidden;-webkit-transform:translateZ(0);transform:translateZ(0)}.i-amphtml-image-lightbox-viewer-image{position:absolute;z-index:1;display:block;-webkit-transform-origin:50% 50%;transform-origin:50% 50%}\n/*# sourceURL=/extensions/amp-image-lightbox/0.1/amp-image-lightbox.css*/")})(self.AMP);
})});
//# sourceMappingURL=amp-image-lightbox-0.1.js.map

