(self.AMP=self.AMP||[]).push({n:"amp-user-notification",v:"1522422854768",f:(function(AMP){var g;function h(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};function l(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];if(e instanceof Error&&!b){var b=void 0,k=e.message,f=String(Math.random());e.message=f;if(e.message===f)e.message=k,b=e;else{k=Error(e.message);for(b in e)k[b]=e[b];k.stack=e.stack;b=k}}else c&&(c+=" "),c+=e}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}function m(a){var b=l.apply(null,arguments);setTimeout(function(){self.reportError(b);throw b;})}self.log=self.log||{user:null,dev:null,userForEmbed:null};
var p=self.log;function q(){if(!p.user)throw Error("failed to call initLogConstructor");return p.user}function r(){if(p.dev)return p.dev;throw Error("failed to call initLogConstructor");};function t(a){return a||{}};function u(a){this.O=a;this.h=Object.create(null)}u.prototype.get=function(a){if(this.h[a])return this.h[a].access=Date.now(),this.h[a].payload};u.prototype.put=function(a,b){var c=this;this.h[a]={payload:b,access:Date.now()};var d=Object.keys(this.h);d.length>this.O&&(r().warn("lru-cache","Trimming template cache"),d.sort(function(a,b){return c.h[b].access-c.h[a].access}),delete this.h[d[d.length-1]])};t({c:!0,v:!0,a:!0,ad:!0});var v,w;
function x(a){if("string"==typeof a){v||(v=self.document.createElement("a"),w=self.UrlCache||(self.UrlCache=new u(100)));var b=w.get(a);if(b)a=b;else{b=v;b.href=a;b.protocol||(b.href=b.href);var c={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:"0"==b.port?"":b.port,pathname:b.pathname,search:b.search,hash:b.hash,origin:null};"/"!==c.pathname[0]&&(c.pathname="/"+c.pathname);if("http:"==c.protocol&&80==c.port||"https:"==c.protocol&&443==c.port)c.port="",c.host=c.hostname;c.origin=
b.origin&&"null"!=b.origin?b.origin:"data:"!=c.protocol&&c.host?c.protocol+"//"+c.host:c.href;w.put(a,c);a=c}}(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}
function y(a,b){var c;c=void 0===c?"source":c;q().assert(null!=a,"%s %s must be available",b,c);var d=a;q().assert(x(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)};function z(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView;if(b=b!=(b.__AMP_TOP||b)&&A(b,"url-replace")?B(b,"url-replace"):null)return b}return D(a,"url-replace")}function E(a,b){a=a.__AMP_TOP||a;return B(a,b)}function D(a,b){a=F(a);a=G(a);return B(a,b)}function F(a){return a.nodeType?E((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function G(a){a=F(a);return a.isSingleDoc()?a.win:a}
function B(a,b){A(a,b);var c=H(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function I(a,b){var c=J(a,b);if(c)return c;var d,e=new Promise(function(a){d=a});H(a)[b]={obj:null,promise:e,resolve:d,context:null,ctor:null};return e}function J(a,b){var c=H(a)[b];if(c){if(c.promise)return c.promise;B(a,b);return c.promise=Promise.resolve(c.obj)}return null}function H(a){var b=a.services;b||(b=a.services={});return b}
function A(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var K,L="Webkit webkit Moz moz ms O o".split(" ");function M(){this.o=0;this.L=Promise.resolve();this.J=function(){};this.K=function(){}}M.prototype.onQueueEmpty=function(a){this.J=a};M.prototype.onQueueNotEmpty=function(a){this.K=a};M.prototype.registerUI=function(a){var b=this;0==this.o&&this.K();this.o++;var c=this.L.then(function(){return a().then(function(){b.o--;0==b.o&&b.J()})});return this.L=c};function N(a){var b;b=AMP.BaseElement.call(this,a)||this;b.F=null;b.l=null;b.A=null;b.G=new Promise(function(a){b.A=a});b.j=null;b.B=!1;b.m=null;b.C="";b.D=null;b.N=null;return b}h(N,AMP.BaseElement);g=N.prototype;g.isAlwaysFixed=function(){return!0};
g.buildCallback=function(){var a=this,b=this.getAmpDoc();this.N=z(b);this.D=I(G(b),"storage");this.l=q().assert(this.element.id,"amp-user-notification should have an id.");this.C="amp-user-notification:"+this.l;(this.m=this.element.getAttribute("data-show-if-href"))&&y(this.m,this.element);(this.j=this.element.getAttribute("data-dismiss-href"))&&y(this.j,this.element);var c=this.element.getAttribute("role");c||this.element.setAttribute("role","alert");var d=this.element.getAttribute("data-persist-dismissal");
this.B="false"!=d&&"no"!=d;this.registerAction("dismiss",function(){return a.dismiss(!1)});this.registerAction("optoutOfCid",function(){return O(a)});var e=I(G(b),"userNotificationManager");e.then(function(b){b.registerUserNotification(a.l,a)})};
function P(a,b){var c=a.m;return a.N.expandUrlAsync(c).then(function(c){var e;e={elementId:a.l,ampUserId:b};var d=[],f;for(f in e){var n=e[f];if(null!=n)if(Array.isArray(n))for(var C=0;C<n.length;C++){var S=n[C];d.push(encodeURIComponent(f)+"="+encodeURIComponent(S))}else d.push(encodeURIComponent(f)+"="+encodeURIComponent(n))}e=d.join("&");d=c;e?(d=d.split("#",2),f=d[0].split("?",2),e=f[0]+(f[1]?"?"+f[1]+"&"+e:"?"+e),e+=d[1]?"#"+d[1]:""):e=d;return e})}
g.P=function(a){var b=this;this.F=a;return P(this,a).then(function(a){var c={credentials:"include",requireAmpResponseSourceOrigin:!1};return E(b.win,"xhr").fetchJson(a,c).then(function(a){return a.json()})})};function Q(a){var b=a.element.getAttribute("enctype")||"application/json;charset=utf-8";E(a.win,"xhr").fetchJson(a.j,{method:"POST",credentials:"include",requireAmpResponseSourceOrigin:!1,body:t({elementId:a.l,ampUserId:a.F}),headers:{"Content-Type":b}})}
g.S=function(a){q().assert("boolean"==typeof a.showNotification,'`showNotification` should be a boolean. Got "%s" which is of type %s.',a.showNotification,typeof a.showNotification);a.showNotification||this.A();return Promise.resolve(a.showNotification)};function O(a){return I(G(a.element),"cid").then(function(a){return a.optOut()}).then(function(){return a.dismiss(!1)},function(b){r().error("amp-user-notification","Failed to opt out of Cid",b);a.dismiss(!0)})}
function R(a){return I(G(a.element),"cid").then(function(b){return b.get({scope:"amp-user-notification",createCookieIfNotPresent:!0},Promise.resolve(),a.G)})}g.shouldShow=function(){var a=this;return this.isDismissed().then(function(b){return b?!1:a.m?R(a).then(a.P.bind(a)).then(a.S.bind(a)):!0})};
g.show=function(){var a=this.element,b;b=a.style;K||(K=Object.create(null));var c=K.display;if(!c){c="display";if(void 0===b.display){var d;b:{for(d=0;d<L.length;d++){var e=L[d]+"Display";if(void 0!==b[e]){d=e;break b}}d=""}void 0!==b[d]&&(c=d)}K.display=c}b=c;b&&(a.style[b]="");this.element.classList.add("amp-active");this.getViewport().addToFixedLayer(this.element);return this.G};
g.isDismissed=function(){var a=this;return this.B?this.D.then(function(b){return b.get(a.C)}).then(function(a){return!!a},function(a){r().error("amp-user-notification","Failed to read storage",a);return!1}):Promise.resolve(!1)};g.activate=function(){this.dismiss(!1)};
g.dismiss=function(a){var b=this;this.element.classList.remove("amp-active");this.element.classList.add("amp-hidden");this.A();this.getViewport().removeFromFixedLayer(this.element);this.B&&!a&&this.D.then(function(a){a.set(b.C,!0)});this.j&&Q(this)};function T(a){this.ampdoc=a;this.M=Object.create(null);this.w=Object.create(null);this.T=D(this.ampdoc,"viewer");this.H=this.ampdoc.whenReady();this.I=Promise.all([this.T.whenFirstVisible(),this.H]);this.R=I(G(this.ampdoc),"notificationUIManager")}
T.prototype.get=function(a){var b=this;this.I.then(function(){null==b.ampdoc.getElementById(a)&&q().warn("amp-user-notification","Did not find amp-user-notification element "+a+".")});return U(this,a).promise};T.prototype.getNotification=function(a){var b=this;return this.H.then(function(){return b.M[a]})};
T.prototype.registerUserNotification=function(a,b){var c=this;this.M[a]=b;var d=U(this,a);return this.I.then(function(){return b.shouldShow()}).then(function(a){if(a)return c.R.then(function(a){return a.registerUI(b.show.bind(b))})}).then(d.resolve.bind(this,b)).catch(m.bind(null,"Notification service failed amp-user-notification",a))};function U(a,b){if(a.w[b])return a.w[b];var c,d=new Promise(function(a){c=a});return a.w[b]={promise:d,resolve:c}}
(function(a){a.registerServiceForDoc("userNotificationManager",T);a.registerServiceForDoc("notificationUIManager",M);a.registerElement("amp-user-notification",N,"amp-user-notification{position:fixed!important;bottom:0;left:0;overflow:hidden!important;visibility:hidden;background:hsla(0,0%,100%,0.7);z-index:1000;width:100%}amp-user-notification.amp-active{visibility:visible}amp-user-notification.amp-hidden{visibility:hidden}\n/*# sourceURL=/extensions/amp-user-notification/0.1/amp-user-notification.css*/")})(self.AMP);
})});
//# sourceMappingURL=amp-user-notification-0.1.js.map

