(self.AMP=self.AMP||[]).push({n:"amp-facebook",v:"1522422854768",f:(function(AMP){function aa(a,b){function e(){}e.prototype=b.prototype;a.prototype=new e;a.prototype.constructor=a;for(var c in b)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c]}function w(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(e){return b}};var ba=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function x(a){var b=Object.create(null);if(!a)return b;for(var e;e=ba.exec(a);){var c=w(e[1],e[1]),d=e[2]?w(e[2],e[2]):"";b[c]=d}return b};var z="";function A(){var a=void 0,b=a||self,e;if(b.AMP_MODE)e=b.AMP_MODE;else{e=b;var c=x(e.location.originalHash||e.location.hash),d=x(e.location.search);z||(z=e.AMP_CONFIG&&e.AMP_CONFIG.v?e.AMP_CONFIG.v:"011522422854768");e=b.AMP_MODE={localDev:!1,development:!("1"!=c.development&&!e.AMP_DEV_MODE),examiner:"2"==c.development,filter:c.filter,minified:!0,lite:void 0!=d.amp_lite,test:!1,log:c.log,version:"1522422854768",rtvVersion:z}}return e};self.log=self.log||{user:null,dev:null,userForEmbed:null};var B=self.log;function C(){if(!B.user)throw Error("failed to call initLogConstructor");return B.user}function D(){if(B.dev)return B.dev;throw Error("failed to call initLogConstructor");};function E(a){return a||{}};function F(a){this.l=a;this.h=Object.create(null)}F.prototype.get=function(a){if(this.h[a])return this.h[a].access=Date.now(),this.h[a].payload};F.prototype.put=function(a,b){var e=this;this.h[a]={payload:b,access:Date.now()};var c=Object.keys(this.h);c.length>this.l&&(D().warn("lru-cache","Trimming template cache"),c.sort(function(a,b){return e.h[b].access-e.h[a].access}),delete this.h[c[c.length-1]])};function H(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var I=self.AMP_CONFIG||{},J=I.thirdPartyUrl||"https://3p.ampproject.net",ca=I.thirdPartyFrameHost||"ampproject.net";E({c:!0,v:!0,a:!0,ad:!0});var K,L;
function M(a){var b;K||(K=self.document.createElement("a"),L=self.UrlCache||(self.UrlCache=new F(100)));var e=L.get(a);if(e)return e;var c=K;c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=c.origin&&
"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;var g=d,f=g;if(b)return f;L.put(a,f);return f}function da(a){"string"==typeof a&&(a=M(a));var b;(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b};function N(a,b){try{return JSON.parse(a)}catch(e){b&&b(e)}};function O(a,b){a=P(a);a=P(a);a=a.isSingleDoc()?a.win:a;return Q(a,b)}function P(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView,b=b.__AMP_TOP||b;a=Q(b,"ampdoc").getAmpDoc(a)}return a}function Q(a,b){var e=a.services;e||(e=a.services={});var c=e;a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function ea(a){a:{var b;try{b=a.document.cookie}catch(h){b=""}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var e=a[b].trim(),c=e.indexOf("="),d;if(d=-1!=c)d=e.substring(0,c).trim(),d="AMP_EXP"==w(d,void 0);if(d){a=e.substring(c+1).trim();a=w(a,a);break a}}a=null}var g=a,f=g?g.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<f.length;b++)0!=f[b].length&&("-"==f[b][0]?a[f[b].substr(1)]=!1:a[f[b]]=!0);return a};function fa(a){for(var b=a.nodeName,e=0,c=0,d=a.previousElementSibling;d&&25>c&&100>e;)d.nodeName==b&&c++,e++,d=d.previousElementSibling;return 25>c&&100>e?"."+c:""};var R,S="Webkit webkit Moz moz ms O o".split(" ");function ga(a){var b,e;e=a.style;if(H("border","--"))e="border";else{R||(R=Object.create(null));var c=R.border;if(!c){c="border";if(void 0===e.border){var d;b:{for(d=0;d<S.length;d++){var g=S[d]+"Border";if(void 0!==e[g]){d=g;break b}}d=""}void 0!==e[d]&&(c=d)}R.border=c}e=c}e&&(a.style[e]=b?"none"+b:"none")};function T(a){a=parseFloat(a);return"number"===typeof a&&isFinite(a)?a:void 0};var U={};
function ha(a,b){C().assert("facebook","Attribute type required for <amp-ad>: %s",b);for(var e=0,c=a;c&&c!=c.parent;c=c.parent)e++;var e=String(e)+"-"+V(a),d=c={},g=b.dataset,f;for(f in g)H(f,"vars")||(d[f]=g[f]);if(f=b.getAttribute("json")){f=N(f);if(void 0===f)throw C().createError("Error parsing JSON in json attribute in element %s",b);for(var h in f)d[h]=f[h]}h=c;c=Date.now();d=b.getAttribute("width");f=b.getAttribute("height");h=h?h:{};h.width=T(d);h.height=T(f);b.getAttribute("title")&&(h.title=
b.getAttribute("title"));var r=a.location.href;"about:srcdoc"==r&&(r=a.parent.location.href);var t=O(b,"documentInfo").get(),u=O(b,"viewer"),d=u.getUnconfirmedReferrerUrl(),p=b.getPageLayoutBox();f=h;for(var g=t.sourceUrl,m=t.canonicalUrl,t=t.pageViewId,r={href:r},G=b.tagName,y={localDev:!1,development:A().development,filter:A().filter,minified:!0,lite:A().lite,test:!1,log:A().log,version:A().version,rtvVersion:A().rtvVersion},ia=!(!a.AMP_CONFIG||!a.AMP_CONFIG.canary),u=!u.isVisible(),p=p?{left:p.left,
top:p.top,width:p.width,height:p.height}:null,ja=b.getIntersectionChangeEntry(),n=b,q=[],k=0;n&&1==n.nodeType&&25>k;){var l="";n.id&&(l="/"+n.id);var ka=n.nodeName.toLowerCase();q.push(""+ka+l+fa(n));k++;n=n.parentElement}n=q.join();q=n.length;k=5381;for(l=0;l<q;l++)k=33*k^n.charCodeAt(l);n=String(k>>>0);if(a.__AMP__EXPERIMENT_TOGGLES)a=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);q=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var v in a.AMP_CONFIG)k=a.AMP_CONFIG[v],
"number"===typeof k&&0<=k&&1>=k&&(q[v]=Math.random()<k);if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(v=a.AMP_CONFIG["allow-doc-opt-in"],k=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(k=k.getAttribute("content").split(","),l=0;l<k.length;l++)-1!=v.indexOf(k[l])&&(q[k[l]]=!0);Object.assign(q,ea(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length)for(v=
a.AMP_CONFIG["allow-url-opt-in"],a=x(a.location.originalHash||a.location.hash),k=0;k<v.length;k++)l=a["e-"+v[k]],"1"==l&&(q[v[k]]=!0),"0"==l&&(q[v[k]]=!1);a=q}f._context=E({ampcontextVersion:"1522422854768",ampcontextFilepath:J+"/1522422854768/ampcontext-v0.js",sourceUrl:g,referrer:d,canonicalUrl:m,pageViewId:t,location:r,startTime:c,tagName:G,mode:y,canary:ia,hidden:u,initialLayoutRect:p,initialIntersection:ja,domFingerprint:n,experimentToggles:a,sentinel:e});(b=b.getAttribute("src"))&&
(h.src=b);c=h;c.type="facebook";Object.assign(c._context,void 0);return c}
function la(a,b){var e,c=ha(a,b),d=a.document.createElement("iframe");U[c.type]||(U[c.type]=0);U[c.type]+=1;a=W(a,"facebook",e);var g=M(a).hostname,f=JSON.stringify(E({host:g,type:c.type,count:U[c.type],attributes:c}));d.src=a;d.ampLocation=M(a);d.name=f;c.width&&(d.width=c.width);c.height&&(d.height=c.height);c.title&&(d.title=c.title);d.setAttribute("scrolling","no");ga(d);d.onload=function(){this.readyState="complete"};d.setAttribute("data-amp-3p-sentinel",c._context.sentinel);return d}
function W(a,b,e){var c=void 0,d=a.bootstrapBaseUrl;if(d)a=d;else{var g;g=c;var f=a.document.querySelector('meta[name="amp-3p-iframe-src"]');if(f)if(e)C().error("3p-frame","3p iframe url disabled for "+(b||"unknown")),g=null;else{b=f.getAttribute("content");var h;h=void 0===h?"source":h;C().assert(null!=b,"%s %s must be available",f,h);C().assert(da(b)||/^(\/\/)/.test(b),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',f,h,
b);C().assert(-1==b.indexOf("?"),"3p iframe url must not include query string %s in element %s.",b,f);h=M(b);C().assert("localhost"==h.hostname&&!g||h.origin!=M(a.location.href).origin,"3p iframe url must not be on the same origin as the current document %s (%s) in element %s. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.",b,h.origin,f);g=b+"?1522422854768"}else g=null;g||(a.defaultBootstrapSubDomain=a.defaultBootstrapSubDomain||"d-"+
V(a),g="https://"+a.defaultBootstrapSubDomain+("."+ca+"/1522422854768/")+"frame.html");a=a.bootstrapBaseUrl=g}return a}function V(a){var b;if(a.crypto&&a.crypto.getRandomValues){var e=new Uint32Array(2);a.crypto.getRandomValues(e);b=String(e[0])+e[1]}else b=String(a.Math.random()).substr(2)+"0";return b};function ma(a){if(!X(a))return null;var b=a.indexOf("{");try{return JSON.parse(a.substr(b))}catch(e){return D().error("MESSAGING","Failed to parse message: "+a,e),null}}function X(a){return"string"==typeof a&&0==a.indexOf("amp-")&&-1!=a.indexOf("{")};function Y(a,b,e){var c=a.listeningFors;!c&&e&&(c=a.listeningFors=Object.create(null));a=c||null;if(!a)return a;var d=a[b];!d&&e&&(d=a[b]=[]);return d||null}function na(a,b){var e=!0,c=M(b.src).origin,d=e?b.getAttribute("data-amp-3p-sentinel"):"amp";a=Y(a,d,!0);for(var g,d=0;d<a.length;d++){var f=a[d];if(f.frame===b){g=f;break}}g||(g={frame:b,origin:c,events:Object.create(null)},a.push(g));return g.events}
function oa(a){for(var b=E({sentinel:"unlisten"}),e=a.length-1;0<=e;e--){var c=a[e];if(!c.frame.contentWindow){a.splice(e,1);var d=c.events,g;for(g in d)d[g].splice(0,Infinity).forEach(function(a){a(b)})}}}
function pa(a){if(!a.listeningFors){var b=function(b){if(b.data){var c=qa(b.data);if(c&&c.sentinel){var d;d=c.sentinel;var e=b.origin,f=b.source,h=Y(a,d);if(h){for(var r,t=0;t<h.length;t++){var u=h[t],p=u.frame.contentWindow;if(p)if("amp"===d){if(u.origin===e&&p==f){r=u;break}}else{var m;if(!(m=f==p))b:{for(m=f;m&&m!=m.parent;m=m.parent)if(m==p){m=!0;break b}m=!1}if(m){r=u;break}}else setTimeout(oa,0,h)}d=r?r.events:null}else d=h;var G=d;if(G){var y=G[c.type];if(y)for(y=y.slice(),d=0;d<y.length;d++)(0,y[d])(c,
b.source,b.origin)}}}};a.addEventListener("message",b)}}function ra(a,b){function e(d,e,f){if(c||e==a.contentWindow)"unlisten"==d.sentinel?h():b(d,e,f)}var c,d="embed-size",g=a.ownerDocument.defaultView;pa(g);var g=na(g,a),f=g[d]||(g[d]=[]),h;f.push(e);h=function(){if(e){var a=f.indexOf(e);-1<a&&f.splice(a,1);b=f=e=null}}}
function qa(a){"string"==typeof a&&(a="{"==a.charAt(0)?N(a,function(a){D().warn("IFRAME-HELPER","Postmessage could not be parsed. Is it in a valid JSON format?",a)})||null:X(a)?ma(a):null);return a};function Z(a){var b;b=AMP.BaseElement.call(this,a)||this;b.j=null;a=a.hasAttribute("data-locale")?a.getAttribute("data-locale"):window.navigator.language.replace("-","_");b.m=a;return b}aa(Z,AMP.BaseElement);Z.prototype.renderOutsideViewport=function(){return.75};
Z.prototype.preconnectCallback=function(a){this.preconnect.url("https://facebook.com",a);this.preconnect.preload("https://connect.facebook.net/"+this.m+"/sdk.js","script");var b=this.preconnect,e=W(this.win,void 0,void 0);b.preload(e,"document");b.preload(J+"/1522422854768/f.js","script")};Z.prototype.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};
Z.prototype.layoutCallback=function(){var a=this,b=la(this.win,this.element);this.applyFillContent(b);ra(b,function(b){a.changeHeight(b.height)});this.element.appendChild(b);this.j=b;return this.loadPromise(b)};Z.prototype.unlayoutOnPause=function(){return!0};Z.prototype.unlayoutCallback=function(){if(this.j){var a=this.j;a.parentElement&&a.parentElement.removeChild(a);this.j=null}return!0};(function(a){a.registerElement("amp-facebook",Z)})(self.AMP);
})});
//# sourceMappingURL=amp-facebook-0.1.js.map

